# Provisional Analysis

Analyze dataset to gain insight into the following questions:

1. **Conversion rate**: What percentage of unique site visitors make a purchase?
2. **Top Channel Groupings**: What are the top channelgroupings for each country?
3. **Most Viewed Products**: What are the top 10 products based on unique visitor viewings?
4. **Most Frequent Visitors**: How many visits did the top 10 unique site visitors make?
5. **Timeonsite Trends**: How does average timeonsite differ between visitor who did and did not make a purchase?

In [ ]:
import pandas as pd

#### Load iPython-SQL module

In [ ]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql


#### Customize query output settings

In [ ]:
%%html
<style>
    table {
        table-layout: auto; /* Table width adjusts to fit output columns */
        width: auto; /* Column width adjusts to cell contents */
    }

    table td, table th {
        white-space: nowrap; /* Prevent text wrapping within cells */
        text-align: left; /* Left-align cell contents */
    }
</style>

### Connect to database

In [ ]:
%sql postgresql://postgres:12345@localhost/ecomm_cleanse

# Conversion Rate

- determine what percentage of unique visitors make a purchase using
    - A) analytics table
    - B) all_sessions table
- explain data quality issues that may affect the confidence/accuracy of this answer

## all_sessions table

In [214]:
%%sql

SELECT * FROM all_sessions LIMIT 3;

 * postgresql://postgres:***@localhost/ecomm_cleanse
3 rows affected.


[('2817722496551184128', 'Direct', '122213', 'Taiwan', '(not set)', None, None, '142', '7', None, datetime.date(2016, 9, 13), '1473757371', 'PAGE', None, Decimal('2.99'), None, 'GGOEGAAX0074', 'Google 22 oz Water Bottle', 'Home/Drinkware/', '(not set)', 'USD', None, None, 'Drinkware', '/google+redesign/', '0', '1', None),
 ('6938960486452471698', 'Referral', '268947', 'United States', 'not available in demo dataset', None, None, '269', '6', None, datetime.date(2017, 4, 21), '1492809942', 'PAGE', None, Decimal('98.99'), None, 'GGOEGAAX0607', "Google Women's Convertible Vest-Jacket Sea Foam Green", "Home/Apparel/Women's/", '(not set)', 'USD', None, None, "Women's Apparel | Google Merchandise Store", '/google+redesign/', '0', '1', None),
 ('5307554331754279093', 'Organic Search', '61402', 'United States', 'not available in demo dataset', None, None, '61', '6', None, datetime.date(2017, 3, 12), '1489340747', 'PAGE', None, Decimal('24.99'), None, 'GGOEGHPA003010', 'Google Wool Heather Cap Heather/Navy', 'Home/Apparel/Headgear/', '(not set)', 'USD', None, None, 'Headgear | Apparel | Google Merchandise Store', '/google+redesign/', '0', '1', None)]

In [215]:
all_sessions_df = _.DataFrame()

In [216]:
all_sessions_df.columns

Index(['fullvisitorid', 'channelgrouping', 'time', 'country', 'city',
       'totaltransactionrevenue', 'transactions', 'timeonsite', 'pageviews',
       'sessionqualitydim', 'date', 'visitid', 'type', 'productquantity',
       'productprice', 'productrevenue', 'productsku', 'v2productname',
       'v2productcategory', 'productvariant', 'currencycode',
       'transactionrevenue', 'transactionid', 'pagetitle', 'pagepathlevel1',
       'ecommerceactiontype', 'ecommerceactionstep', 'ecommerceactionoption'],
      dtype='object')

To answer question we need:
- count of all unique visitors
    - what determines a unique visitor? assume `fullvisitorid`
- count of unique visitors who have made a transaction
    - relevant cols: `transactions`, `transactionrevenue`, `totaltransactionrevenue`

In [49]:
%%sql

SELECT visitid, totaltransactionrevenue, transactions, transactionrevenue, productrevenue
FROM all_sessions
WHERE totaltransactionrevenue IS NOT NULL
LIMIT 10;

 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[('1479318391', Decimal('305.00'), '1', None, None),
 ('1487816197', Decimal('152.00'), '1', None, None),
 ('1473206048', Decimal('13.21'), '1', None, None),
 ('1474892406', Decimal('32.18'), '1', None, None),
 ('1481645890', Decimal('742.48'), '1', None, None),
 ('1495668283', Decimal('26.82'), '1', None, None),
 ('1488667799', Decimal('747.00'), '1', None, None),
 ('1494587162', Decimal('16.99'), '1', None, None),
 ('1489992840', Decimal('200.00'), '1', Decimal('200.00'), Decimal('120.00')),
 ('1490046065', Decimal('124.00'), '1', None, None)]

- lets confirm if `transactions` always conforms to the above query, (= '1' when `totaltransactionrevenue` is non-null)

In [43]:
%%sql

SELECT COUNT(*)
FROM all_sessions
WHERE totaltransactionrevenue IS NOT NULL
    AND transactions != '1';

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(0,)]

- from the above query, we can confirm that `transactions` = '1' whenever `totaltransactionrevenue` is non-null

- lets now filter for non-null `transactionrevenue` and `productrevenue` to see how they correlate

In [52]:
%%sql

SELECT visitid, totaltransactionrevenue, transactionrevenue, productrevenue, productquantity, productprice
FROM all_sessions
WHERE transactionrevenue IS NOT NULL
    OR productrevenue IS NOT NULL;

 * postgresql://postgres:***@localhost/ecomm_cleanse
4 rows affected.


[('1489992840', Decimal('200.00'), Decimal('200.00'), Decimal('120.00'), '1', Decimal('119.00')),
 ('1491424130', Decimal('169.97'), Decimal('169.97'), Decimal('58.66'), '1', Decimal('55.99')),
 ('1478007873', Decimal('1015.48'), Decimal('1015.48'), Decimal('176.40'), '50', Decimal('3.50')),
 ('1481693637', Decimal('1005.50'), Decimal('1005.50'), Decimal('60.37'), '1', Decimal('59.99'))]

- from the above query we can make the following correlations:
    - `transactionrevenue` and `productrevenue` are only non-null when `totaltransactionrevenue` is non-null
    - `transactionrevenue` = `totaltransactionrevenue` in all occurences
    - `productrevenue` ~ `productquantity` x `productprice`
        - the small differences here could be tax, transaction fees, or some other variable not captured in this table, but represents a data quality issue

- for the purposes of calculating the % of unique visitors who make a purchase, we can isolate `totaltransactionrevenue` and assume it is an indicator of a transaction taking place

- lets get a count of unique visitors in the `all_sessions` table:

In [218]:
%%sql

SELECT
    COUNT(DISTINCT fullvisitorid)
FROM
    all_sessions
WHERE
    totaltransactionrevenue IS NOT NULL;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(80,)]

- one of the fullvisitor ids has a duplicate (80 vs the 81 records with non-null totaltransactionrevenue)
- lets find which one and look at their activity

In [219]:
%%sql 

SELECT
    SUM(transactions) AS num_transactions,
    fullvisitorid
FROM
    all_sessions
WHERE
    transactions IS NOT NULL
GROUP BY
    fullvisitorid
ORDER BY
    num_transactions DESC
LIMIT 3;
    

 * postgresql://postgres:***@localhost/ecomm_cleanse
(psycopg2.errors.UndefinedFunction) function sum(text) does not exist
LINE 2:     SUM(transactions) AS num_transactions,
            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT
    SUM(transactions) AS num_transactions,
    fullvisitorid
FROM
    all_sessions
WHERE
    transactions IS NOT NULL
GROUP BY
    fullvisitorid
ORDER BY
    num_transactions DESC
LIMIT 3;]
(Background on this error at: https://sqlalche.me/e/20/f405)


the only unique visitor (`fullvisitorid`) who made more than one purchase is `3764227345226401562`

In [53]:
%%sql

SELECT * FROM all_sessions WHERE fullvisitorid = '3764227345226401562';

 * postgresql://postgres:***@localhost/ecomm_cleanse
2 rows affected.


[('3764227345226401562', 'Direct', '0', 'United States', 'not available in demo dataset', Decimal('124.00'), '1', '342', '12', None, datetime.date(2017, 3, 20), '1490046065', 'PAGE', None, Decimal('249.00'), None, 'GGOEGAAX0794', 'Nest® Learning Thermostat 3rd Gen-USA', 'Home/Nest/Nest-USA/', '(not set)', 'USD', None, None, 'Nest-USA', '/google+redesign/', '0', '1', None),
 ('3764227345226401562', 'Direct', '342254', 'United States', 'not available in demo dataset', Decimal('124.00'), '1', '342', '12', None, datetime.date(2017, 3, 20), '1490046065', 'PAGE', None, Decimal('119.00'), None, 'GGOENEBB078899', 'Nest® Cam Indoor Security Camera - USA', 'Nest-USA', 'Single Option Only', 'USD', None, 'ORD201703201986', 'Checkout Confirmation', '/ordercompleted.html', '6', '1', None)]

inspecting the two records from this unique visitor shows that it is likely a duplicate transaction, not two distinct purchases. therefore there are only 80 transactions so far. this raises doubts about the validity of the other transactions.

we can see differenences in `productsku`, `v2productname`, `v2productcategory`, and many other columns that are null in one of the two records.

lets inspect the list of records with transactions and include other visit info to see if we can catch any other obvious discrepancies

- lets quickly get a count of how many records with transactions have a `transactionid`

In [61]:
%%sql

SELECT (
    SELECT COUNT(*)
    FROM all_sessions
    WHERE transactionid IS NOT NULL
) as num_transactionids,
(
    SELECT COUNT(*)
    FROM all_sessions
    WHERE transactions IS NOT NULL
) as num_transactions;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(9, 81)]

- from the above query, we can see there's clearly an issue with missing transactionids

In [221]:
%%sql

SELECT * 
FROM all_sessions
WHERE transactions IS NOT NULL
ORDER BY date, time
LIMIT 10;

 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[('4934955623514361329', 'Referral', '0', 'United States', 'San Francisco', Decimal('139.42'), '1', '280', '14', None, datetime.date(2016, 8, 10), '1470870890', 'PAGE', None, Decimal('12.99'), None, 'GGOEADWQ015699', 'Android Rise 14 oz Mug', 'Home/Accessories/Drinkware/', '(not set)', 'USD', None, None, 'Drinkware', '/google+redesign/', '0', '1', None),
 ('0375962687766031488', 'Organic Search', '311843', 'United States', 'not available in demo dataset', Decimal('27.49'), '1', '331', '14', None, datetime.date(2016, 8, 11), '1470980004', 'PAGE', None, Decimal('16.99'), None, 'GGOEGAAX0105', "Google Men's 100% Cotton Short Sleeve Hero Tee Black", 'Home/Shop by Brand/Google/', '(not set)', 'USD', None, None, 'Google', '/google+redesign/', '0', '1', None),
 ('4088086075239844129', 'Organic Search', '0', 'United States', 'not available in demo dataset', Decimal('13.21'), '1', '297', '11', None, datetime.date(2016, 9, 6), '1473206048', 'PAGE', None, Decimal('19.99'), None, 'GGOEGBMB073799', 'Google Zipper-front Sports Bag', 'Home/Bags/', '(not set)', 'USD', None, None, 'Bags', '/google+redesign/', '0', '1', None),
 ('5795630000736964663', 'Referral', '72872', 'United States', 'Mountain View', Decimal('13.39'), '1', '473', '18', None, datetime.date(2016, 9, 16), '1474057380', 'PAGE', None, Decimal('13.59'), None, 'GGOEGEGQ024299', 'Grip Kit Cable Organizer', 'Home/Electronics/Electronics Accessories/', '(not set)', 'USD', None, None, 'Electronics Accessories', '/google+redesign/', '0', '1', None),
 ('803888563485194008', 'Referral', '8713', 'United States', 'not available in demo dataset', Decimal('32.18'), '1', '422', '10', None, datetime.date(2016, 9, 26), '1474892406', 'PAGE', None, Decimal('15.19'), None, 'GGOEGAAX0293', "Android Women's Short Sleeve Tri-blend Badge Tee Light Grey", "Home/Apparel/Women's/Women's-T-Shirts/", '(not set)', 'USD', None, None, "Women's-T-Shirts", '/google+redesign/', '0', '1', None),
 ('8293848749722274504', 'Direct', '10864', 'United States', 'New York', Decimal('32.99'), '1', '1512', '11', None, datetime.date(2016, 9, 28), '1475088529', 'PAGE', None, Decimal('23.99'), None, 'GGOEGAAX0610', 'Google Onesie Red/Graphite', "Home/Apparel/Kid's/Kid's-Infant/", '(not set)', 'USD', None, None, "Kid's-Infant", '/google+redesign/', '0', '1', None),
 ('7524696809408974105', 'Organic Search', '71478', 'United States', 'Houston', Decimal('38.98'), '1', '508', '18', None, datetime.date(2016, 10, 7), '1475869577', 'PAGE', None, Decimal('24.99'), None, 'GGOEGDHQ015399', '26 oz Double Wall Insulated Bottle', 'Home/Drinkware/', '(not set)', 'USD', None, None, 'Drinkware | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('1250309821000380040', 'Organic Search', '270744', 'United States', 'Columbus', Decimal('21.99'), '1', '368', '14', None, datetime.date(2016, 10, 11), '1476201122', 'PAGE', '1', Decimal('18.99'), None, 'GGOEGAAJ032617', "Google Men's Short Sleeve Badge Tee Charcoal", '(not set)', ' 2XL', 'USD', None, None, 'Checkout Your Information', '/yourinfo.html', '5', '1', 'Billing and Shipping'),
 ('7078772937328563719', 'Organic Search', '0', 'United States', 'not available in demo dataset', Decimal('38.99'), '1', '442', '15', None, datetime.date(2016, 10, 14), '1476502145', 'PAGE', None, Decimal('37.99'), None, 'GGOEGAAX0627', 'Google Infant Zip Hood Pink', "Home/Apparel/Kid's/Kid's-Infant/", '(not set)', 'USD', None, None, "Infant | Kids' Apparel | Google Merchandise Store", '/google+redesign/', '0', '1', None),
 ('9095439474545827790', 'Organic Search', '42182', 'United States', 'San Francisco', Decimal('23.99'), '1', '270', '15', None, datetime.date(2016, 10, 20), '1476976393', 'PAGE', None, Decimal('39.99'), None, 'GGOEGAAX0313', 'Google Tri-blend Hoodie Grey', "Home/Apparel/Men's/Men's-Outerwear/", '(not set)', 'USD', None, None, "Men's Outerwear | Apparel | Google Merchandise Store", '/google+redesign/', '0', '1', None)]

- no apparent patterns of obvious duplicates from inspecting the above. (similar transactions made on the same day)

- lets see if there are duplicate visitids among records with transactions

In [222]:
%%sql

SELECT
    visitid,
    COUNT(DISTINCT fullvisitorid) AS num_fullvisitorid
FROM all_sessions
WHERE transactions IS NOT NULL
GROUP BY visitid
HAVING COUNT(fullvisitorid) > 1
ORDER BY visitid;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[('1490046065', 1)]

- its the same as the duplicate we've already found
- lets assum that the rest of the records with transactions are not duplicates (so 80 purchases in total)



- so how many unique visitors are there?

In [223]:
%%sql

-- unique visitors who have made a transaction
SELECT
    COUNT(DISTINCT fullvisitorid) AS num_fullvisitorid
FROM all_sessions
WHERE transactions IS NOT NULL;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(80,)]

In [224]:
%%sql

-- total unique visitors
SELECT
    COUNT(DISTINCT fullvisitorid) AS num_fullvisitorid
FROM all_sessions;


 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(14223,)]

In [225]:
%%sql

-- how many visitids appear in more than one row/record
SELECT
    COUNT(*)
FROM (
    SELECT
        visitid,
        COUNT(*)
    FROM all_sessions
    GROUP BY visitid
    HAVING COUNT(*) > 1
    ORDER BY visitid
);


 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(553,)]

In [226]:
%%sql

-- inspect a visitid with multiple records
SELECT visitid, COUNT(*)
FROM all_sessions
GROUP BY visitid
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC, visitid
LIMIT 10;


 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[('1471780519', 4),
 ('1474392675', 4),
 ('1470721493', 3),
 ('1471254087', 3),
 ('1471371097', 3),
 ('1471465622', 3),
 ('1471499344', 3),
 ('1471541027', 3),
 ('1471809022', 3),
 ('1472711033', 3)]

In [227]:
%%sql
-- inspect the 2 modal visitids (4 records each)
SELECT *
FROM all_sessions
WHERE visitid IN ('1471780519', '1474392675')
ORDER BY date, time;

 * postgresql://postgres:***@localhost/ecomm_cleanse
8 rows affected.


[('3879633557713030804', 'Organic Search', '137434', 'United States', 'New York', None, None, '151', '6', None, datetime.date(2016, 8, 21), '1471780519', 'PAGE', None, Decimal('6.99'), None, 'GGOEYOLR018699', 'YouTube Leatherette Notebook Combo', 'Home/Office/', '(not set)', 'USD', None, None, 'Office', '/google+redesign/', '0', '1', None),
 ('3879633557713030804', 'Organic Search', '32178', 'United States', 'New York', None, None, '151', '6', None, datetime.date(2016, 8, 21), '1471780519', 'PAGE', None, Decimal('4.99'), None, 'GGOEYDHJ056099', '22 oz YouTube Bottle Infuser', 'Home/Drinkware/', '(not set)', 'USD', None, None, 'Drinkware', '/google+redesign/', '0', '1', None),
 ('3879633557713030804', 'Organic Search', '58188', 'United States', 'New York', None, None, '151', '6', None, datetime.date(2016, 8, 21), '1471780519', 'PAGE', None, Decimal('22.99'), None, 'GGOEGEHQ072499', 'Google 2200mAh Micro Charger', 'Home/Electronics/', '(not set)', 'USD', None, None, 'Electronics', '/google+redesign/', '0', '1', None),
 ('3879633557713030804', 'Organic Search', '58188', 'United States', 'New York', None, None, '151', '6', None, datetime.date(2016, 8, 21), '1471780519', 'PAGE', None, Decimal('16.99'), None, 'GGOEGESC014699', 'Aluminum Handy Emergency Flashlight', 'Home/Electronics/', '(not set)', 'USD', None, None, 'Electronics', '/google+redesign/', '0', '1', None),
 ('3288547201266617821', 'Direct', '109254', 'United States', 'not available in demo dataset', None, None, '134', '9', None, datetime.date(2016, 9, 20), '1474392675', 'PAGE', None, Decimal('119.99'), None, 'GGOEGAAX0585', "Google Women's Insulated Thermal Vest Navy", 'Home/Apparel/', '(not set)', 'USD', None, None, 'Apparel', '/store.html', '0', '1', None),
 ('3288547201266617821', 'Direct', '119992', 'United States', 'not available in demo dataset', None, None, '134', '9', None, datetime.date(2016, 9, 20), '1474392675', 'PAGE', None, Decimal('39.99'), None, 'GGOEGAAX0310', 'Google Heavyweight Long Sleeve Hero Tee Burgundy', 'Home/Apparel/', '(not set)', 'USD', None, None, 'Apparel', '/google+redesign/', '0', '1', None),
 ('3288547201266617821', 'Direct', '119992', 'United States', 'not available in demo dataset', None, None, '134', '9', None, datetime.date(2016, 9, 20), '1474392675', 'PAGE', None, Decimal('18.99'), None, 'GGOEGAAX0289', "Google Women's Short Sleeve Shirt Dark Grey", 'Home/Apparel/', '(not set)', 'USD', None, None, 'Apparel', '/google+redesign/', '0', '1', None),
 ('3288547201266617821', 'Direct', '57437', 'United States', 'not available in demo dataset', None, None, '134', '9', None, datetime.date(2016, 9, 20), '1474392675', 'PAGE', None, Decimal('21.99'), None, 'GGOEGHPA002910', 'Google Trucker Hat', 'Home/Apparel/', '(not set)', 'USD', None, None, 'Apparel', '/google+redesign/', '0', '1', None)]

- the visitid above looked at 4 different `productsku`
    - each product/page viewing gets its own record
    - `timeonsite` and `pageviews` values appear to apply to the `visitid` / whole session, and not to a pageviewing
        - `time` is still ambiguous, but has duplicate values for records where the `productsku` differs

- to determine which visits were duplicates, we would have to compare the `visitids` that appear multiple times, but only 1 distinct `productsku`

In [228]:
%%sql
-- return visitids and count of associated records
WITH multiple_records AS (
    SELECT
        visitid,
        COUNT(*)
    FROM all_sessions
    GROUP BY visitid
    HAVING COUNT(*) > 1
)
-- return visitid that have multiple records but only 1 productsku, (potential duplicates)
SELECT visitid, COUNT(DISTINCT productsku) AS num_productsku
FROM all_sessions
WHERE visitid IN (SELECT visitid FROM multiple_records)
GROUP BY visitid
HAVING COUNT(DISTINCT productsku) = 1
ORDER BY visitid;

 * postgresql://postgres:***@localhost/ecomm_cleanse
5 rows affected.


[('1481233332', 1),
 ('1489797382', 1),
 ('1493605322', 1),
 ('1493909433', 1),
 ('1495005901', 1)]

In [229]:
%%sql
CREATE TEMPORARY VIEW visitid_productsku_dupe AS (
-- return visitids and count of associated records
WITH multiple_records AS (
    SELECT
        visitid,
        COUNT(*)
    FROM all_sessions
    GROUP BY visitid
    HAVING COUNT(*) > 1
)
-- return visitid that have multiple records but only 1 productsku, (potential duplicates)
SELECT visitid, COUNT(DISTINCT productsku) AS num_productsku
FROM all_sessions
WHERE visitid IN (SELECT visitid FROM multiple_records)
GROUP BY visitid
HAVING COUNT(DISTINCT productsku) = 1
ORDER BY visitid
);

 * postgresql://postgres:***@localhost/ecomm_cleanse
Done.


[]

In [230]:
%%sql

SELECT *
FROM all_sessions
WHERE visitid IN (SELECT visitid FROM visitid_productsku_dupe)
ORDER BY visitid, date, time;

 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[('1704532013850009944', 'Direct', '129197', 'United States', 'Mountain View', None, None, '581', '13', None, datetime.date(2016, 12, 8), '1481233332', 'PAGE', None, Decimal('249.00'), None, 'GGOENEBJ079499', 'Nest® Learning Thermostat 3rd Gen-USA - Stainless Steel', 'Nest-USA', 'Single Option Only', 'USD', None, None, 'Payment Method', '/payment.html', '5', '2', 'Payment'),
 ('1704532013850009944', 'Direct', '35362', 'United States', 'Mountain View', None, None, '581', '13', None, datetime.date(2016, 12, 8), '1481233332', 'EVENT', '1', Decimal('249.00'), None, 'GGOENEBJ079499', 'Nest® Learning Thermostat 3rd Gen-USA - Stainless Steel', 'Home/Nest/Nest-USA/', '(not set)', 'USD', None, None, 'Nest-USA', '/google+redesign/', '3', '1', None),
 ('3390845580595254860', 'Affiliates', '20361', 'Indonesia', 'Jakarta', None, None, '40', '3', None, datetime.date(2017, 3, 17), '1489797382', 'PAGE', None, Decimal('8.99'), None, 'GGOEAOCH014199', 'Android Journal Book Set', 'Home/Shop by Brand/Android/', '(not set)', 'USD', None, None, 'Android | Shop by Brand | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('3390845580595254860', 'Affiliates', '39905', 'Indonesia', 'Jakarta', None, None, '40', '3', None, datetime.date(2017, 3, 17), '1489797382', 'PAGE', None, Decimal('8.99'), None, 'GGOEAOCH014199', 'Android Journal Book Set', 'Home/Shop by Brand/Android/', '(not set)', 'USD', None, None, 'Android | Shop by Brand | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('0868696744816935480', 'Referral', '40655', 'United States', 'Mountain View', None, None, '79', '7', None, datetime.date(2017, 4, 30), '1493605322', 'PAGE', None, Decimal('18.99'), None, 'GGOEGHPJ080110', 'Google 5-Panel Cap', 'Home/Apparel/', '(not set)', 'USD', None, None, 'Apparel | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('0868696744816935480', 'Referral', '78594', 'United States', 'Mountain View', None, None, '79', '7', None, datetime.date(2017, 4, 30), '1493605322', 'PAGE', None, Decimal('18.99'), None, 'GGOEGHPJ080110', 'Google 5-Panel Cap', 'Home/Apparel/', '(not set)', 'USD', None, None, 'Apparel | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('9921250175298945406', 'Organic Search', '108926', 'United States', 'not available in demo dataset', None, None, '160', '4', None, datetime.date(2017, 5, 4), '1493909433', 'PAGE', None, Decimal('20.99'), None, 'GGOEGAAX0355', "Google Men's Vintage Tank", "Home/Apparel/Men's/Men's-T-Shirts/", '(not set)', 'USD', None, None, "Men's T-Shirts | Apparel | Google Merchandise Store", '/google+redesign/', '0', '1', None),
 ('9921250175298945406', 'Organic Search', '159541', 'United States', 'not available in demo dataset', None, None, '160', '4', None, datetime.date(2017, 5, 4), '1493909433', 'PAGE', None, Decimal('20.99'), None, 'GGOEGAAX0355', "Google Men's Vintage Tank", "Home/Apparel/Men's/Men's-T-Shirts/", '(not set)', 'USD', None, None, "Men's T-Shirts | Apparel | Google Merchandise Store", '/google+redesign/', '0', '1', None),
 ('5355700591805934083', 'Referral', '13230', 'United States', 'Mountain View', None, None, '31', '3', None, datetime.date(2017, 5, 17), '1495005901', 'PAGE', None, Decimal('6.99'), None, 'GGOEGCBB074199', 'Google Car Clip Phone Holder', 'Home/Electronics/Electronics Accessories/', '(not set)', 'USD', None, None, 'Accessories | Electronics | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('5355700591805934083', 'Referral', '30527', 'United States', 'Mountain View', None, None, '31', '3', None, datetime.date(2017, 5, 17), '1495005901', 'PAGE', None, Decimal('6.99'), None, 'GGOEGCBB074199', 'Google Car Clip Phone Holder', 'Home/Shop by Brand/Google/', '(not set)', 'USD', None, None, 'Google | Shop by Brand | Google Merchandise Store', '/google+redesign/', '0', '1', None)]

**visitid = 1481233332**
- not a duplicate, the records differ by `type`, `productquantity`, `ecommerceactionstep`, `ecommerceactionoption`, `ecommerceactiontype`
    - this might represent a popup payment window, or add to cart action

**visitid IN (1489797382, 1493605322, 1493909433, 1495005901)**
- only differs by `time`, the remaining columns are identical. these might represent true duplicate records
    - if this is the case, we can remove records that only differ by `time` column, however, its uncertain which `time` value to keep

- lets investigate how `time` and `timeonsite` correlate to determine what `time` represents

In [231]:
%%sql
-- isolate visitids with multiple records
WITH multiple_visitids AS (
    SELECT visitid, COUNT(*)
    FROM all_sessions
    GROUP BY visitid
    HAVING COUNT(*) > 1
    ORDER BY COUNT(*) DESC, visitid
)
-- return the time and timeonsite values for each visitid
SELECT visitid, time, timeonsite, pageviews--, v2productname, productsku
FROM all_sessions
WHERE visitid IN (SELECT visitid FROM multiple_visitids)
ORDER BY visitid, time
LIMIT 30;

 * postgresql://postgres:***@localhost/ecomm_cleanse
30 rows affected.


[('1470042235', '0', '41', '4'),
 ('1470042235', '40817', '41', '4'),
 ('1470093166', '29826', '91', '6'),
 ('1470093166', '75635', '91', '6'),
 ('1470152438', '166779', '186', '7'),
 ('1470152438', '4232', '186', '7'),
 ('1470157307', '0', '111', '4'),
 ('1470157307', '28506', '111', '4'),
 ('1470174905', '72451', '105', '6'),
 ('1470174905', '72451', '105', '6'),
 ('1470222606', '1298874', '1368', '7'),
 ('1470222606', '1319892', '1368', '7'),
 ('1470250539', '28349', '35', '5'),
 ('1470250539', '6773', '35', '5'),
 ('1470266781', '82140', '107', '8'),
 ('1470266781', '82140', '107', '8'),
 ('1470285826', '0', None, '1'),
 ('1470285826', '0', None, '1'),
 ('1470295887', '152612', '178', '8'),
 ('1470295887', '91493', '178', '8'),
 ('1470333871', '0', '39', '4'),
 ('1470333871', '4409', '39', '4'),
 ('1470339528', '138545', '193', '4'),
 ('1470339528', '193119', '193', '4'),
 ('1470349168', '34295', '107', '7'),
 ('1470349168', '36167', '107', '7'),
 ('1470374447', '94418', '132', '6'),
 ('1470374447', '94418', '132', '6'),
 ('1470374662', '19249', '95', '6'),
 ('1470374662', '19249', '95', '6')]

- lets explore the above data to see how `time` and `timeonsite` correlate

In [232]:
# create dataframe from above query
df = _.DataFrame()

# filter out rows with null timeonsite values
df = df[df['timeonsite'].notnull()]

# convert time and timeonsite to numeric
df['time'] = pd.to_numeric(df['time'])
df['timeonsite'] = pd.to_numeric(df['timeonsite'])

# calculate correlation coefficient of time and timeonsite
correlation = df['time'].corr(df['timeonsite'])

print(correlation)

0.9935047889587217


- `time` and `timeonsite` are correlated almost perfectly (R = .994)
    - `time` then represents the _"timeonpage"_, for that particular product page in milliseconds, `timeonesite` then represents the duration of visit
        -  `pageviews` does not correlate to this the amount of records a `visitid` has in this table, so its likely that `all_sessions` table is meant for **product focused** interactions
            - this also explains why we can't sum `time` / 1000 for a given `visitid` to equal the `timeonsite` value, as we don't have the `time` values for each page in the total `pageviews`
                - `analytics` table contains more records, likely representing every page view, a more comprehensive collection of visitor actions, not just the product focused activity

- we still can't safely remove `visitid` duplicates with differing `time` values, we'll need to look at the `analytics` table to see which is the correct value, or if these represent clicking back and forth onto the same product page.

### duplicate visitid, time, different productsku

In [233]:
%%sql

SELECT * FROM all_sessions WHERE visitid = '1471044901';

 * postgresql://postgres:***@localhost/ecomm_cleanse
2 rows affected.


[('2009336688383047852', 'Organic Search', '95842', 'United States', 'San Francisco', None, None, '105', '6', None, datetime.date(2016, 8, 12), '1471044901', 'PAGE', None, Decimal('16.99'), None, 'GGOEGAAX0286', "Google Women's Short Sleeve V-Neck Tee Black", "Home/Apparel/Women's/", '(not set)', 'USD', None, None, "Women's", '/store.html', '0', '1', None),
 ('2009336688383047852', 'Organic Search', '95842', 'United States', 'San Francisco', None, None, '105', '6', None, datetime.date(2016, 8, 12), '1471044901', 'PAGE', None, Decimal('16.99'), None, 'GGOEGAAX0342', "Google Women's Hero V-Neck Tee White", "Home/Apparel/Women's/", '(not set)', 'USD', None, None, "Women's", '/store.html', '0', '1', None)]

- records are identical except for `productsku` and `v2productname`, this represents looking at 2 color options for the same product
    - have identical `time` values, assume that this is the same product page, and the visitor is viewing different product variants (note that `productvariant` is not set, another data quality issue)

### `fullvisitorid` / `visitid` relationship

- if fullvisitorid represents a unique visitor, and visitid represents a unique visit:
    - visitids should only belong to one fullvisitorid
- lets check if any visitids have multiple fullvisitorids

In [234]:
%%sql

SELECT
    visitid,
    COUNT(DISTINCT fullvisitorid) AS num_fullvisitorid
FROM all_sessions
GROUP BY visitid
HAVING COUNT(DISTINCT fullvisitorid) > 1
ORDER BY COUNT(DISTINCT fullvisitorid) DESC, visitid;

 * postgresql://postgres:***@localhost/ecomm_cleanse
5 rows affected.


[('1472245964', 2),
 ('1481056958', 2),
 ('1486495918', 2),
 ('1489390306', 2),
 ('1493984498', 2)]

- there are 5 `visitid`s that have multiple `fullvisitorid`s
- since this is so few, we can assume that this is data integrity issue, and that `visitid`s are meant to be unique to a `fullvisitorid`.

In [13]:
%%sql

WITH visitid_with_multiple_fullvisitorids AS (
    SELECT
        visitid,
        COUNT(DISTINCT fullvisitorid) AS num_fullvisitorid
    FROM all_sessions
    GROUP BY visitid
    HAVING COUNT(DISTINCT fullvisitorid) > 1
)

SELECT *
FROM all_sessions
WHERE visitid IN (SELECT visitid FROM visitid_with_multiple_fullvisitorids)
ORDER BY visitid, date, time;

 * postgresql://postgres:***@localhost/ecomm_cleanse
11 rows affected.


[('1564859784344874077', 'Display', '128076', 'United States', 'San Jose', None, None, '381', '12', None, datetime.date(2016, 8, 26), '1472245964', 'PAGE', None, Decimal('16.99'), None, 'GGOEGAAX0340', "Google Men's Vintage Badge Tee Green", 'Home/Shop by Brand/Google/', '(not set)', 'USD', None, None, 'Google', '/google+redesign/', '0', '1', None),
 ('3068325344054598197', 'Referral', '142913', 'United States', 'Los Angeles', None, None, '143', '9', None, datetime.date(2016, 8, 26), '1472245964', 'PAGE', None, Decimal('20.99'), None, 'GGOEGAAX0355', "Google Men's Vintage Tank", "Home/Apparel/Men's/Men's-T-Shirts/", '(not set)', 'USD', None, None, "Men's-T-Shirts", '/google+redesign/', '0', '1', None),
 ('4779983800431086057', 'Organic Search', '10883', 'United States', 'not available in demo dataset', None, None, '11', '3', None, datetime.date(2016, 12, 6), '1481056958', 'PAGE', None, Decimal('16.99'), None, 'GGOEGAAX0278', "Google Women's Short Sleeve Hero Tee Black", 'Home/Shop by Brand/Google/', '(not set)', 'USD', None, None, 'Google | Shop by Brand | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('8461696435976971245', 'Referral', '84628', 'United States', 'Mountain View', None, None, '85', '2', None, datetime.date(2016, 12, 6), '1481056958', 'PAGE', None, Decimal('79.00'), None, 'GGOENEBQ079099', 'Nest® Protect Smoke + CO White Battery Alarm-USA', 'Home/Nest/Nest-USA/', '(not set)', 'USD', None, None, 'Nest-USA', '/google+redesign/', '0', '1', None),
 ('9883320447773379187', 'Organic Search', '0', 'France', 'not available in demo dataset', None, None, None, '1', None, datetime.date(2017, 2, 7), '1486495918', 'PAGE', None, Decimal('7.99'), None, 'GGOEYDHJ019399', '24 oz YouTube Sergeant Stripe Bottle', 'Home/Shop by Brand/YouTube/', '(not set)', 'USD', None, None, 'YouTube | Shop by Brand | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('0342510849516555866', 'Organic Search', '14060', 'Panama', 'not available in demo dataset', None, None, '380', '10', None, datetime.date(2017, 2, 7), '1486495918', 'PAGE', None, Decimal('17.99'), None, 'GGOEACCQ017299', 'Android Lunch Kit', 'Home/Shop by Brand/Android/', '(not set)', 'USD', None, None, 'Android | Shop by Brand | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('9745924027985023690', 'Direct', '191393', 'Taiwan', '(not set)', None, None, '191', '6', None, datetime.date(2017, 3, 13), '1489390306', 'PAGE', None, Decimal('1.99'), None, 'GGOEYFKQ020699', 'YouTube Custom Decals', 'Home/Accessories/', '(not set)', 'USD', None, None, 'Accessories | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('3145922112411660552', 'Direct', '46200', 'Taiwan', '(not set)', None, None, '46', '3', None, datetime.date(2017, 3, 13), '1489390306', 'PAGE', None, Decimal('1.99'), None, 'GGOEGFYQ016599', 'Foam Can and Bottle Cooler', 'Home/Accessories/Housewares/', '(not set)', 'USD', None, None, 'Housewares | Accessories | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('7210036159326579347', 'Direct', '21258', 'Finland', 'not available in demo dataset', None, None, '21', '3', None, datetime.date(2017, 5, 5), '1493984498', 'PAGE', None, Decimal('29.99'), None, 'GGOEGAAX0353', 'Google Vintage Henley Grey/Black', "Home/Apparel/Men's/", '(not set)', 'USD', None, None, "Men's Apparel | Google Merchandise Store", '/google+redesign/', '0', '1', None),
 ('039119641538796794', 'Organic Search', '21523', 'United States', 'Chicago', None, None, '44', '4', None, datetime.date(2017, 5, 5), '1493984498', 'PAGE', None, Decimal('12.99'), None, 'GGOEADWQ015699', 'Android Rise 14 oz Mug', 'Home/Shop by Brand/Android/', '(not set)', 'USD', None, None, 'Android | Shop by Brand | Google Merchandise Store', '/google+redesign/', '0', '1', None),
 ('039119641538796794', 'Organic Search', '21523', 'United States', 'Chicago', None, None, '44', '4', None, datetime.date(2017, 5, 5), '1493984498', 'PAGE', None, Decimal('24.99'), Non

- from manually inspecting the above query, the only thing these `visitid`s that are assigned to multiple `fullvisitorid`s share in common is the `date`
    - because these offending `visitid`s have different `country` values, we can infer they aren't duplicates, but instead an error with id assignment
    - assumming `visitid`s are assigned in chronological order, is possible that there was a system error during `visitid` assignment (if two distinct visitors entered the site at precisely the same time, and were both assigned the same `visitid` by error. this would be worth bringing up with the associated engineers to let them know of this error)

- from examining these discrepancies, 

In [236]:
%%sql

-- find the highest and lowest visitid values and compare the dates

SELECT
    MIN(visitid) AS min_visitid,
    MAX(visitid) AS max_visitid,
    MIN(date) AS min_date,
    MAX(date) AS max_date
FROM all_sessions;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[('1470037277', '1501657186', datetime.date(2016, 8, 1), datetime.date(2017, 8, 1))]

In [237]:
%%sql

SELECT visitid, date
FROM all_sessions
WHERE visitid IN ('1470037277', '1501657186')

 * postgresql://postgres:***@localhost/ecomm_cleanse
2 rows affected.


[('1501657186', datetime.date(2017, 8, 1)),
 ('1470037277', datetime.date(2016, 8, 1))]

- from the above we can see that visitids are indeed assigned in chronological order, the largest visitid is associated with the latest date, and vice versa

### `all_sessions` conversion rate
- lets just try to answer the question: what percentage of unique visitors make a purchase, based on the `all_sessions` table

to calculate this, we need COUNT(DISTINCT fullvisitorid WHERE transaction IS NOT NULL) / COUNT(DISTINCT fullvisitorid)

In [286]:
%%sql
-- count of unique visitors (fullvisitorids) who have made a transaction
SELECT
    COUNT(DISTINCT fullvisitorid)
FROM
    all_sessions
WHERE
    totaltransactionrevenue IS NOT NULL;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(80,)]

- 80 visitors made a purchase

In [14]:
%%sql
-- count of all unique visitors (fullvisitorids)
SELECT
    COUNT(DISTINCT fullvisitorid)
FROM
    all_sessions

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(14223,)]

In [15]:
conversion_rate = (80 / 14223) * 100

round(conversion_rate, 2)

0.56

If we assume there are no issues with `fullvisitorid` representing unique site visitors, then, according to the `all_sessions` table, **0.56% of unique visitors have made a purchase** (transaction)

## analytics table

- lets now try to perform the same calculation using the data found in the analytics table

In [241]:
%%sql

SELECT * FROM analytics LIMIT 3;

 * postgresql://postgres:***@localhost/ecomm_cleanse
3 rows affected.


[('7', '1498424366', '1498424366', '20170625', '9444016982622091039', None, 'Display', 'Not Socially Engaged', None, '1', None, '1', None, '8990000'),
 ('7', '1498424366', '1498424366', '20170625', '9444016982622091039', None, 'Display', 'Not Socially Engaged', None, '1', None, '1', None, '10990000'),
 ('7', '1498424366', '1498424366', '20170625', '9444016982622091039', None, 'Display', 'Not Socially Engaged', None, '1', None, '1', None, '10990000')]

In [242]:
df = _.DataFrame()

df.columns

Index(['visitnumber', 'visitid', 'visitstarttime', 'date', 'fullvisitorid',
       'userid', 'channelgrouping', 'socialengagementtype', 'unitssold',
       'pageviews', 'timeonsite', 'bounces', 'revenue', 'unitprice'],
      dtype='object')

- first lets determine the denominator (total unique visitors), again using fullvisitorid

In [243]:
%%sql

SELECT COUNT(DISTINCT fullvisitorid)
FROM analytics

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(120018,)]

- here's our first red flag, there are 120,018 unique `fullvisitorid`s in the `analytics` table, vs only 14,223 found in the `all_sessions` table.
    - if our datasets don't agree, we can't be confident of how many unique visitors have been to the site, or if `fullvisitorid` can be reliably used as a way to count unique visitors
    - its possible that `analytics` table has a larger date range, accounting for this difference. lets check
        - we know from previous queries in `all_sessions` that it's dates range from 2016-08-01 to 2017-08-01, a 12 month period

In [16]:
%%sql

SELECT
    MIN(date) AS min_date,
    MAX(date) AS max_date
FROM analytics;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(datetime.date(2017, 5, 1), datetime.date(2017, 8, 1))]

- we can see from the above result that `analytics` actually has a ***smaller*** date range, consisting of only 3 months (2017-05-01 to 2017-08-01)
    - this is concerning. assumming that `analytics` and `all_sessions` are tracking the same site visitors, the fact that `analytics` contains almost 10x the amount of unique users, while containing data for only 1/4 of the date range, that means that all_sessions is missing the vast majority of unique visitors, and so our conversion rate calculation is almost certainly misleading

- lets continue our preliminary calculation of conversion rate, using `analytics` table
    - the only data we have available in `analytics` to determine if a transaction occurred seems to be `unitssold` and `revenue`, so our next query will filter for that

In [17]:
%%sql

SELECT *
FROM analytics
WHERE unitssold IS NOT NULL OR revenue IS NOT NULL
ORDER BY visitid, date, visitnumber
LIMIT 20;

 * postgresql://postgres:***@localhost/ecomm_cleanse
20 rows affected.


[('16', '1493621769', '1493622340', datetime.date(2017, 5, 1), '8178386963876992406', 'Referral', 'Not Socially Engaged', '1', '2', None, None, Decimal('157.00'), Decimal('149.00')),
 ('1', '1493621869', '1493622050', datetime.date(2017, 5, 1), '1198068166576036308', 'Organic Search', 'Not Socially Engaged', '1', '6', '180', None, None, Decimal('14.69')),
 ('2', '1493622552', '1493622552', datetime.date(2017, 5, 1), '6161000104029164017', 'Organic Search', 'Not Socially Engaged', '1', '10', '1078', None, None, Decimal('2.99')),
 ('1', '1493622674', '1493622674', datetime.date(2017, 5, 1), '3981344185539559220', 'Organic Search', 'Not Socially Engaged', '1', '13', '287', None, None, Decimal('19.99')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '4', '19', '376', None, None, Decimal('119.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '3', '19', '376', None, None, Decimal('237.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '2', '19', '376', None, None, Decimal('158.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '3', '19', '376', None, Decimal('242.00'), Decimal('79.00')),
 ('1', '1493629794', '1493629794', datetime.date(2017, 5, 1), '0167440527318407308', 'Organic Search', 'Not Socially Engaged', '1', '6', '359', None, None, Decimal('16.99')),
 ('2', '1493630490', '1493630490', datetime.date(2017, 5, 1), '7580688081499541991', 'Social', 'Not Socially Engaged', '1', '7', '328', None, None, Decimal('33.59')),
 ('3', '1493634816', '1493634816', datetime.date(2017, 5, 1), '0089335119897729017', 'Organic Search', 'Not Socially Engaged', '1', '5', '164', None, None, Decimal('10.99')),
 ('2', '1493638822', '1493638822', datetime.date(2017, 5, 1), '9888039975793005488', 'Social', 'Not Socially Engaged', '1', '20', '2081', None, None, Decimal('19.99')),
 ('1', '1493639737', '1493639737', datetime.date(2017, 5, 1), '2847957052786600334', 'Referral', 'Not Socially Engaged', '1', '33', '602', None, None, Decimal('5.99')),
 ('1', '1493639785', '1493639785', datetime.date(2017, 5, 1), '9203923090206958455', 'Organic Search', 'Not Socially Engaged', '1', '6', '295', None, None, Decimal('19.99')),
 ('1', '1493640195', '1493640195', datetime.date(2017, 5, 1), '0948655553332044353', 'Direct', 'Not Socially Engaged', '1', '8', '958', None, None, Decimal('24.99')),
 ('1', '1493641450', '1493641450', datetime.date(2017, 5, 1), '3985304281629561294', 'Referral', 'Not Socially Engaged', '5', '29', '642', None, None, Decimal('3.19')),
 ('1', '1493641450', '1493641450', datetime.date(2017, 5, 1), '3985304281629561294', 'Referral', 'Not Socially Engaged', '3', '29', '642', None, None, Decimal('1.59')),
 ('1', '1493641450', '1493641450', datetime.date(2017, 5, 1), '3985304281629561294', 'Referral', 'Not Socially Engaged', '5', '29', '642', None, None, Decimal('1.20')),
 ('1', '1493641450', '1493641450', datetime.date(2017, 5, 1), '3985304281629561294', 'Referral', 'Not Socially Engaged', '2', '29', '642', None, None, Decimal('10.39')),
 ('1', '1493641450', '1493641450', datetime.date(2017, 5, 1), '3985304281629561294', 'Referral', 'Not Socially Engaged', '3', '29', '642', None, None, Decimal('3.99'))]

- its unclear how we can determine whether `unitssold` or `revenue` can be assigned to a record
    - from the above query, we can see that `unitssold` gets assigned to all records associated with a `visitid`, but revenue is only assigned to a single record
        - `revenue` then might only occur precisely when the visitor finishes the transaction

- there are many records where `unitssold` is not null, yet `revenue` is null. its not clear if either is a reliable indicator of a visit resulting in a transaction
    - its possible that `unitssold` and `revenue` contain false positive, and false negatives. we don't have enough insight yet to rule out either

-- lets inspect a single visitid where there was a non-null `unitssold`, yet no `revenue`

In [18]:
%%sql

SELECT *
FROM analytics
WHERE visitid = '1493629794'
ORDER BY visitid, date, visitnumber
--LIMIT 20;

 * postgresql://postgres:***@localhost/ecomm_cleanse
7 rows affected.


[('1', '1493629794', '1493629794', datetime.date(2017, 5, 1), '0167440527318407308', 'Organic Search', 'Not Socially Engaged', '1', '6', '359', None, None, Decimal('16.99')),
 ('1', '1493629794', '1493629794', datetime.date(2017, 5, 1), '0167440527318407308', 'Organic Search', 'Not Socially Engaged', None, '6', '359', None, None, Decimal('16.99')),
 ('1', '1493629794', '1493629794', datetime.date(2017, 5, 1), '0167440527318407308', 'Organic Search', 'Not Socially Engaged', None, '6', '359', None, None, Decimal('18.99')),
 ('1', '1493629794', '1493629794', datetime.date(2017, 5, 1), '0167440527318407308', 'Organic Search', 'Not Socially Engaged', None, '6', '359', None, None, Decimal('19.99')),
 ('1', '1493629794', '1493629794', datetime.date(2017, 5, 1), '0167440527318407308', 'Organic Search', 'Not Socially Engaged', None, '6', '359', None, None, Decimal('20.99')),
 ('1', '1493629794', '1493629794', datetime.date(2017, 5, 1), '0167440527318407308', 'Organic Search', 'Not Socially Engaged', None, '6', '359', None, None, Decimal('24.99')),
 ('1', '1493629794', '1493629794', datetime.date(2017, 5, 1), '0167440527318407308', 'Organic Search', 'Not Socially Engaged', None, '6', '359', None, None, Decimal('29.99'))]

In [19]:
%%sql

SELECT *
FROM all_sessions
WHERE visitid = '1493629794';

 * postgresql://postgres:***@localhost/ecomm_cleanse
0 rows affected.


[]

- this `visitid` is missing from `all_sessions`, so we can't gain any insight there

- now lets look at records associated with a `visitid` that had a non-null `revenue`

In [20]:
%%sql

SELECT *
FROM analytics
WHERE visitid = '1493627652'
ORDER BY visitid, date, visitnumber
--LIMIT 20;

 * postgresql://postgres:***@localhost/ecomm_cleanse
9 rows affected.


[('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '2', '19', '376', None, None, Decimal('158.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '3', '19', '376', None, Decimal('242.00'), Decimal('79.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '3', '19', '376', None, None, Decimal('237.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '4', '19', '376', None, None, Decimal('119.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', None, '19', '376', None, None, Decimal('119.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', None, '19', '376', None, None, Decimal('199.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', None, '19', '376', None, None, Decimal('237.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', None, '19', '376', None, None, Decimal('249.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', None, '19', '376', None, None, Decimal('79.00'))]

- from the above query, we can see various `unitssold` values can belong to a single `visitid`
- only one record has a non-null `revenue` value
    - this implies that `unitssold` is not an indicator for an actual transaction
        - maybe `unitssold` only indicates that an item was added to the visitors cart/basket?

- lets use non-null `revenue` values to determine the count of unique visitors who made a purchase
- first we'll count the number of records in `analytics` with non-null `revenue`

In [21]:
%%sql

SELECT COUNT(*)
FROM analytics
WHERE revenue IS NOT NULL;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(13419,)]

- that's a lot of records. lets see what they look like (if revenue can be non-null for multiple records with the same `visitid`)

In [22]:
%%sql

SELECT *
FROM analytics
WHERE revenue IS NOT NULL
ORDER BY fullvisitorid, visitid, visitnumber
LIMIT 20;

 * postgresql://postgres:***@localhost/ecomm_cleanse
20 rows affected.


[('2', '1495425682', '1495425682', datetime.date(2017, 5, 21), '0003961110741104601', 'Organic Search', 'Not Socially Engaged', '1', '20', '502', None, Decimal('5.99'), Decimal('2.99')),
 ('2', '1495425682', '1495425682', datetime.date(2017, 5, 21), '0003961110741104601', 'Organic Search', 'Not Socially Engaged', '1', '20', '502', None, Decimal('4.99'), Decimal('1.99')),
 ('2', '1501364305', '1501364305', datetime.date(2017, 7, 29), '0004478134742292937', 'Referral', 'Not Socially Engaged', '1', '27', '1004', None, Decimal('15.49'), Decimal('13.99')),
 ('2', '1501364305', '1501364305', datetime.date(2017, 7, 29), '0004478134742292937', 'Referral', 'Not Socially Engaged', '1', '27', '1004', None, Decimal('14.70'), Decimal('13.20')),
 ('2', '1501364305', '1501364305', datetime.date(2017, 7, 29), '0004478134742292937', 'Referral', 'Not Socially Engaged', '1', '27', '1004', None, Decimal('10.30'), Decimal('8.80')),
 ('2', '1501364305', '1501364305', datetime.date(2017, 7, 29), '0004478134742292937', 'Referral', 'Not Socially Engaged', '1', '27', '1004', None, Decimal('6.30'), Decimal('4.80')),
 ('1', '1501010265', '1501010265', datetime.date(2017, 7, 25), '0007177934947634478', 'Direct', 'Not Socially Engaged', '1', '16', '361', None, Decimal('15.59'), Decimal('13.59')),
 ('1', '1501010265', '1501010265', datetime.date(2017, 7, 25), '0007177934947634478', 'Direct', 'Not Socially Engaged', '1', '16', '361', None, Decimal('21.19'), Decimal('19.19')),
 ('1', '1493664333', '1493664333', datetime.date(2017, 5, 1), '0007933257389091624', 'Direct', 'Not Socially Engaged', '1', '17', '518', None, Decimal('37.59'), Decimal('33.59')),
 ('4', '1500336551', '1500336551', datetime.date(2017, 7, 17), '0010926318104555497', 'Referral', 'Not Socially Engaged', '1', '23', '518', None, Decimal('119.50'), Decimal('119.00')),
 ('4', '1500336551', '1500336551', datetime.date(2017, 7, 17), '0010926318104555497', 'Referral', 'Not Socially Engaged', '1', '23', '518', None, Decimal('149.50'), Decimal('149.00')),
 ('4', '1501262790', '1501262790', datetime.date(2017, 7, 28), '0010944918137684580', 'Referral', 'Not Socially Engaged', '8', '28', '327', None, Decimal('18.00'), Decimal('2.00')),
 ('4', '1501262790', '1501262790', datetime.date(2017, 7, 28), '0010944918137684580', 'Referral', 'Not Socially Engaged', '4', '28', '327', None, Decimal('21.16'), Decimal('4.79')),
 ('4', '1501262790', '1501262790', datetime.date(2017, 7, 28), '0010944918137684580', 'Referral', 'Not Socially Engaged', '4', '28', '327', None, Decimal('26.60'), Decimal('6.15')),
 ('6', '1501646806', '1501646806', datetime.date(2017, 8, 1), '00122544416887869', 'Direct', 'Not Socially Engaged', '2', '24', '996', None, Decimal('29.18'), Decimal('13.59')),
 ('6', '1501646806', '1501646806', datetime.date(2017, 8, 1), '00122544416887869', 'Direct', 'Not Socially Engaged', '1', '24', '996', None, Decimal('15.59'), Decimal('13.59')),
 ('6', '1501646806', '1501646806', datetime.date(2017, 8, 1), '00122544416887869', 'Direct', 'Not Socially Engaged', '3', '24', '996', None, Decimal('42.77'), Decimal('13.59')),
 ('3', '1496460676', '1496460676', datetime.date(2017, 6, 2), '0012561433643490595', 'Paid Search', 'Not Socially Engaged', '1', '30', '458', None, Decimal('4.30'), Decimal('2.80')),
 ('3', '1496460676', '1496460676', datetime.date(2017, 6, 2), '0012561433643490595', 'Paid Search', 'Not Socially Engaged', '1', '30', '458', None, Decimal('3.09'), Decimal('1.59')),
 ('3', '1498605303', '1498605303', datetime.date(2017, 6, 27), '0014262055593378383', 'Referral', 'Not Socially Engaged', '1', '11', '309', None, Decimal('15.51'), Decimal('9.51'))]

- `revenue` can have multiple values for the same `visitid`
    - these likely represent multiple different products being adding to the cart

- lets see if they add up to the value found in `all_sessions.totaltransactionrevenue`

In [23]:
%%sql

SELECT fullvisitorid, visitid, totaltransactionrevenue
FROM all_sessions
WHERE fullvisitorid = '999726098109551386';

 * postgresql://postgres:***@localhost/ecomm_cleanse
0 rows affected.


[]

- the above `fullvisitorid` is missing from all_sessions
    - this is problematic. we can't trust any calculations relating to conversion rate if we can't be certain of the total number of unique visitors, or how many of them have made purchases
    - in fact, none of the first 20 `visitid`s or `fullvisitorid`s appear in all_sessions, we'll have to explore where the tables overlap later on

- for now, lets just get a count of distinct `fullvisitorid`s who have at least one record showing non-null `revenue`

In [26]:
%%sql

SELECT fullvisitorid, COUNT(*)
FROM analytics
WHERE revenue IS NOT NULL
GROUP BY fullvisitorid
HAVING COUNT(*) >= 1
ORDER BY COUNT(*) DESC
LIMIT 10;

 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[('9681060687378784629', 51),
 ('5112369122544987822', 45),
 ('3052828106337222847', 34),
 ('1957458976293878100', 32),
 ('7311242886083854158', 28),
 ('4140559214164857738', 27),
 ('9026840718082010040', 26),
 ('7113011772090059658', 25),
 ('7463172420271311409', 24),
 ('7141139312225559597', 23)]

### `analytics` conversion rate

- `fullvisitorid`s can have many records in `analytics` with non-null `revenue` values
- lets use the full count of the list of `fullvisitorid`s with at least one non-null `revenue` value to represent the number of unique visitors who have made a purchase

In [27]:
%%sql

WITH transacting_visitors AS (
    SELECT fullvisitorid, COUNT(*)
    FROM analytics
    WHERE revenue IS NOT NULL
    GROUP BY fullvisitorid
    HAVING COUNT(*) >= 1
)

SELECT COUNT(*) FROM transacting_visitors;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(5799,)]

- alternatively, we can just get a count of distinct `fullvisitorid`s that have been associated with a non-null `revenue` value, this will prevent counting repeat purchases from the same visitor

In [29]:
%%sql 

SELECT COUNT(DISTINCT fullvisitorid) FROM analytics WHERE revenue IS NOT NULL;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(5799,)]

- now we have the numerator for conversation rate, we just need to count all unique `fullvisitorid`s for the denominator

In [28]:
%%sql

SELECT COUNT(DISTINCT fullvisitorid) FROM analytics;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(120018,)]

In [36]:
analytics_conversion_rate = round(((5799 / 120018) * 100), 2)

print(f'Percentage of unique visitors who have made a purchase: {analytics_conversion_rate}%')

Percentage of unique visitors who have made a purchase: 4.83%


- we can see from the above calculation, that the analytics table gives a very different conversion rate %, with far more unique visitors being associated with a transaction, assumming that a non-null `revenue` value indicates that a transaction took place
- we will directly compare the results from `analytics` and `all_sessions` later in this notebook

### unitssold, revenue

- are there records with non-null `revenue`, yet null `unitssold`?

In [32]:
%%sql

SELECT COUNT(*)
FROM analytics
WHERE revenue IS NOT NULL
    AND unitssold IS NULL;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(0,)]

- from the above query, we can see there are no records where `revenue` is recorded without `unitssold` also having a non-null value

- lets check the inverse, can `revenue` be null when `unitssold` is non-null?

In [33]:
%%sql

SELECT COUNT(*)
FROM analytics
WHERE revenue IS NULL
    AND unitssold IS NOT NULL;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(47435,)]

- from the above query we can see that `unitssold` does not indicate a transaction:
    - there are 47435 records where `revenue` is not null when there is an existing `unitssold` value
    - this likely indicates that `unitssold` gets associated with an entire `visitid`, and `revenue` only appears on the records where the transaction occured (payment/checkout page?)

- lets inspect relevant columns where `unitssold` is not null

In [299]:
%%sql

SELECT date, visitid, pageviews, unitssold, unitprice, revenue
FROM analytics
WHERE unitssold IS NOT NULL
ORDER BY visitid, date
LIMIT 20;

 * postgresql://postgres:***@localhost/ecomm_cleanse
20 rows affected.


[(datetime.date(2017, 5, 1), '1493621769', '2', '1', Decimal('149.00'), Decimal('157.00')),
 (datetime.date(2017, 5, 1), '1493621869', '6', '1', Decimal('14.69'), None),
 (datetime.date(2017, 5, 1), '1493622552', '10', '1', Decimal('2.99'), None),
 (datetime.date(2017, 5, 1), '1493622674', '13', '1', Decimal('19.99'), None),
 (datetime.date(2017, 5, 1), '1493627652', '19', '3', Decimal('237.00'), None),
 (datetime.date(2017, 5, 1), '1493627652', '19', '3', Decimal('79.00'), Decimal('242.00')),
 (datetime.date(2017, 5, 1), '1493627652', '19', '4', Decimal('119.00'), None),
 (datetime.date(2017, 5, 1), '1493627652', '19', '2', Decimal('158.00'), None),
 (datetime.date(2017, 5, 1), '1493629794', '6', '1', Decimal('16.99'), None),
 (datetime.date(2017, 5, 1), '1493630490', '7', '1', Decimal('33.59'), None),
 (datetime.date(2017, 5, 1), '1493634816', '5', '1', Decimal('10.99'), None),
 (datetime.date(2017, 5, 1), '1493638822', '20', '1', Decimal('19.99'), None),
 (datetime.date(2017, 5, 1), '1493639737', '33', '1', Decimal('5.99'), None),
 (datetime.date(2017, 5, 1), '1493639785', '6', '1', Decimal('19.99'), None),
 (datetime.date(2017, 5, 1), '1493640195', '8', '1', Decimal('24.99'), None),
 (datetime.date(2017, 5, 1), '1493641450', '29', '5', Decimal('2.39'), None),
 (datetime.date(2017, 5, 1), '1493641450', '29', '3', Decimal('1.20'), None),
 (datetime.date(2017, 5, 1), '1493641450', '29', '3', Decimal('4.79'), None),
 (datetime.date(2017, 5, 1), '1493641450', '29', '3', Decimal('3.99'), None),
 (datetime.date(2017, 5, 1), '1493641450', '29', '5', Decimal('1.20'), None)]

- here we can see for a given `visitid`, there can be various `unitssold`, with or without a recorded `revenue`

- lets select a `visitid` from this list, and check if there are more records associated with null `unitssold`
    - `visitid` = '1493627652' has 4 records in this query, each with a different `unitprice`, and only one with a `revenue` value

In [34]:
%%sql

SELECT * FROM analytics WHERE visitid = '1493627652'

 * postgresql://postgres:***@localhost/ecomm_cleanse
9 rows affected.


[('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '2', '19', '376', None, None, Decimal('158.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '3', '19', '376', None, Decimal('242.00'), Decimal('79.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '3', '19', '376', None, None, Decimal('237.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', '4', '19', '376', None, None, Decimal('119.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', None, '19', '376', None, None, Decimal('119.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', None, '19', '376', None, None, Decimal('199.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', None, '19', '376', None, None, Decimal('237.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', None, '19', '376', None, None, Decimal('249.00')),
 ('1', '1493627652', '1493627652', datetime.date(2017, 5, 1), '4871408819690446049', 'Direct', 'Not Socially Engaged', None, '19', '376', None, None, Decimal('79.00'))]

- it turns out there are 9 records in the table associated with `visitid` = '1493627652', if we include records with null `unitssold`
    - its likely that unitssold just represents products added to cart (what a terrible name for it in that case)
        - we would have to join it with all_sessions to see if this is the case


## comparing `analytics` and `all_sessions` conversion rates

- from the last two sections, we can see a discrepancy in our calculations
    - `analytics` conversion rate = **4.83%**
    - `all_sessions` conversion rate = **0.56%**

- recall, we found a disparity in `date` ranges between the two tables
    - `all_sessions` date range = **2016-08-01 to 2017-08-01**
    - `analytics` date range = **2017-05-01 to 2017-08-01**

- ignoring, for now, the myriad other data quality issues we've uncovered, lets see if `all_sessions` conversion rate is closer to `analytics` once we filter for the same date range as `analytics`

In [256]:
%%sql
-- find total number of unique visitors in all_sessions, filtering by analytics date range
SELECT COUNT(DISTINCT fullvisitorid)
FROM all_sessions
WHERE date BETWEEN '2017-05-01' AND '2017-08-01';

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(3630,)]

In [37]:
%%sql
-- find total number of unique visitors in all_sessions who made transaction, filtering by analytics date range
SELECT COUNT(DISTINCT fullvisitorid)
FROM all_sessions
WHERE date BETWEEN '2017-05-01' AND '2017-08-01'
    AND totaltransactionrevenue IS NOT NULL;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(22,)]

In [39]:
all_sessions_filtered_conversion_rate = round(((22 / 3630) * 100), 2)

print(f'all_sessions: percentage of unique visitors who make a purchase: {all_sessions_filtered_conversion_rate}%')

all_sessions: percentage of unique visitors who make a purchase: 0.61%


- once we control for the same date range between the `analytics` and `all_sessions` tables (2017-05-01 to 2017-08-01), the disparity in conversion rates decreases slightly, but `all_sessions` still indicates a rate of nearly 10x less that `analytics`
    - these findings are based on the assumption that: `fullvisitorid` represents unique visitors, `all_sessions.totaltransactionrevenue` and `analytics.revenue` can be used to indicate a transaction/purchase occured for a given `visitid`
- so our conclusion about the true conversion rate remains uncertain
- to attempt to resolve this discrepancy, we'll have to join the tables to see how they relate

## Joining `all_sessions` and `analytics`

- to better understand what data is missing, lets filter for `fullvisitorid`s and `visitid`s that appear in both tables

- first lets filter each table for columns that could represent overlapping data, or be used for inferrence
    - e.g., `analytics.revenue` might total to `all_sessions.totaltransactionrevenue` for a given `visitid`

In [40]:
%%sql

SELECT date, fullvisitorid, visitid, visitnumber, pageviews, unitssold, unitprice, revenue
FROM analytics
LIMIT 10;

 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[(datetime.date(2017, 5, 31), '0540825100975159075', '1496290637', '1', '18', None, Decimal('21.99'), None),
 (datetime.date(2017, 5, 31), '0540825100975159075', '1496290637', '1', '18', None, Decimal('22.99'), None),
 (datetime.date(2017, 5, 31), '0540825100975159075', '1496290637', '1', '18', None, Decimal('23.99'), None),
 (datetime.date(2017, 5, 31), '0540825100975159075', '1496290637', '1', '18', None, Decimal('24.99'), None),
 (datetime.date(2017, 5, 31), '0540825100975159075', '1496290637', '1', '18', None, Decimal('2.50'), None),
 (datetime.date(2017, 5, 31), '0540825100975159075', '1496290637', '1', '18', None, Decimal('27.99'), None),
 (datetime.date(2017, 5, 31), '0540825100975159075', '1496290637', '1', '18', None, Decimal('2.99'), None),
 (datetime.date(2017, 5, 31), '0540825100975159075', '1496290637', '1', '18', None, Decimal('29.99'), None),
 (datetime.date(2017, 5, 31), '0540825100975159075', '1496290637', '1', '18', None, Decimal('34.99'), None),
 (datetime.date(2017, 5, 31), '0540825100975159075', '1496290637', '1', '18', None, Decimal('3.50'), None)]

In [41]:
%%sql

SELECT date, fullvisitorid, visitid, pageviews, productquantity, productprice, totaltransactionrevenue
FROM all_sessions
LIMIT 10;

 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[(datetime.date(2016, 9, 13), '2817722496551184128', '1473757371', '7', None, Decimal('2.99'), None),
 (datetime.date(2017, 4, 21), '6938960486452471698', '1492809942', '6', None, Decimal('98.99'), None),
 (datetime.date(2017, 3, 12), '5307554331754279093', '1489340747', '6', None, Decimal('24.99'), None),
 (datetime.date(2017, 2, 15), '5256949873742090146', '1487200514', '5', None, Decimal('76.99'), None),
 (datetime.date(2016, 12, 18), '7549308697995967647', '1482129412', '3', None, Decimal('109.99'), None),
 (datetime.date(2016, 9, 11), '5444913961890272648', '1473660616', '4', None, Decimal('4.99'), None),
 (datetime.date(2017, 4, 13), '914760062456295531', '1492130874', '6', None, Decimal('16.99'), None),
 (datetime.date(2016, 9, 2), '4476811245637991248', '1472834061', '8', None, Decimal('5.99'), None),
 (datetime.date(2017, 6, 28), '5153038635419747224', '1498687471', '2', None, Decimal('18.99'), None),
 (datetime.date(2017, 6, 13), '0719635766852234475', '1497352220', '2', None, Decimal('37.99'), None)]

In [261]:
%%sql

SELECT date, fullvisitorid, visitid, pageviews, productquantity, productprice, totaltransactionrevenue
FROM all_sessions
WHERE date BETWEEN '2017-05-01' AND '2017-08-01'
LIMIT 10;

 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[(datetime.date(2017, 6, 28), '5153038635419747224', '1498687471', '2', None, Decimal('18.99'), None),
 (datetime.date(2017, 6, 13), '0719635766852234475', '1497352220', '2', None, Decimal('37.99'), None),
 (datetime.date(2017, 7, 18), '3311454414003524030', '1500429273', '1', None, Decimal('20.99'), None),
 (datetime.date(2017, 7, 4), '9063370709205682295', '1499225367', '1', None, Decimal('59.99'), None),
 (datetime.date(2017, 7, 3), '4940142805755057940', '1499144554', '4', None, Decimal('11.99'), None),
 (datetime.date(2017, 7, 9), '3780103390321914617', '1499647700', '2', None, Decimal('10.99'), None),
 (datetime.date(2017, 7, 2), '048623635253931278', '1499034720', '4', None, Decimal('16.99'), None),
 (datetime.date(2017, 5, 14), '1299017818756049602', '1494830469', '7', None, Decimal('18.99'), None),
 (datetime.date(2017, 5, 1), '4989821450614702108', '1493639669', '2', None, Decimal('14.99'), None),
 (datetime.date(2017, 5, 5), '6708231818366624063', '1493995088', '4', None, Decimal('55.99'), None)]

In [300]:
%%sql

WITH analytics_rev AS (
    SELECT date, fullvisitorid, visitid, visitnumber, pageviews, unitssold, unitprice, revenue
    FROM analytics
),

all_sessions_rev AS (
    SELECT date, fullvisitorid, visitid, pageviews, productquantity, productprice, totaltransactionrevenue
    FROM all_sessions
    WHERE date BETWEEN '2017-05-01' AND '2017-08-01'
)

SELECT DISTINCT *
FROM analytics_rev ar
JOIN all_sessions_rev asr USING (fullvisitorid, visitid, date, pageviews)
WHERE totaltransactionrevenue IS NOT NULL
AND revenue IS NOT NULL
ORDER BY date, visitid
LIMIT 10;

 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[('1862546724568841127', '1493668365', datetime.date(2017, 5, 1), '17', '1', '1', Decimal('15.99'), Decimal('17.49'), None, Decimal('21.99'), Decimal('81.96')),
 ('1862546724568841127', '1493668365', datetime.date(2017, 5, 1), '17', '1', '1', Decimal('27.99'), Decimal('29.49'), None, Decimal('21.99'), Decimal('81.96')),
 ('2678202602250260805', '1494587162', datetime.date(2017, 5, 12), '14', '1', '1', Decimal('13.99'), Decimal('16.99'), None, Decimal('24.99'), Decimal('16.99')),
 ('8645618706223786939', '1494613832', datetime.date(2017, 5, 12), '15', '4', '1', Decimal('2.39'), Decimal('2.89'), None, Decimal('5.59'), Decimal('8.98')),
 ('8645618706223786939', '1494613832', datetime.date(2017, 5, 12), '15', '4', '1', Decimal('5.59'), Decimal('6.09'), None, Decimal('5.59'), Decimal('8.98')),
 ('0348842070964414318', '1494618681', datetime.date(2017, 5, 12), '13', '5', '1', Decimal('67.19'), Decimal('71.19'), None, Decimal('55.99'), Decimal('71.19')),
 ('5635635846003176783', '1494701566', datetime.date(2017, 5, 13), '12', '1', '1', Decimal('119.00'), Decimal('123.00'), None, Decimal('119.00'), Decimal('123.00')),
 ('5961512277421237379', '1494979981', datetime.date(2017, 5, 16), '10', '2', '1', Decimal('15.99'), Decimal('16.99'), '1', Decimal('15.99'), Decimal('16.99')),
 ('299679623448520578', '1495027160', datetime.date(2017, 5, 17), '19', '3', '1', Decimal('16.99'), Decimal('18.66'), None, Decimal('19.99'), Decimal('61.97')),
 ('299679623448520578', '1495027160', datetime.date(2017, 5, 17), '19', '3', '1', Decimal('19.99'), Decimal('21.66'), None, Decimal('19.99'), Decimal('61.97'))]

- how many `fullvisitorid`s are exclusive to `analytics` and `all_sessions`, respectively?

- lets create views that contain the list of unique visitors for each table, over the overlapping date range

In [303]:
%%sql

CREATE OR REPLACE TEMPORARY VIEW as_fullvisitorids AS (
    SELECT DISTINCT fullvisitorid
    FROM all_sessions
    WHERE date BETWEEN '2017-05-01' AND '2017-08-01'
);

CREATE OR REPLACE TEMPORARY VIEW a_fullvisitorids AS (
    SELECT DISTINCT fullvisitorid
    FROM analytics
);

CREATE OR REPLACE TEMPORARY VIEW as_visitids AS (
    SELECT DISTINCT visitid
    FROM all_sessions
    WHERE date BETWEEN '2017-05-01' AND '2017-08-01'
);

CREATE OR REPLACE TEMPORARY VIEW a_visitids AS (
    SELECT DISTINCT visitid
    FROM analytics
);

 * postgresql://postgres:***@localhost/ecomm_cleanse
Done.
Done.
Done.
Done.


[]

- now we can combine these to get the list of all unique visitors, and unique visit for the date range

In [304]:
%%sql

CREATE OR REPLACE TEMPORARY VIEW all_fullvisitorids AS (
    SELECT fullvisitorid
    FROM as_fullvisitorids
    UNION
    SELECT fullvisitorid
    FROM a_fullvisitorids
);

CREATE OR REPLACE TEMPORARY VIEW all_visitids AS (
    SELECT visitid
    FROM as_visitids
    UNION
    SELECT visitid
    FROM a_visitids
);

 * postgresql://postgres:***@localhost/ecomm_cleanse
Done.
Done.


[]

- now lets make lists of unique visitors and visits that are exclusive to each table

In [305]:
%%sql
CREATE OR REPLACE TEMPORARY VIEW a_exclusive_fvid AS (
    SELECT fullvisitorid
    FROM a_fullvisitorids
    EXCEPT
    SELECT fullvisitorid
    FROM as_fullvisitorids
);

CREATE OR REPLACE TEMPORARY VIEW as_exclusive_fvid AS (
    SELECT fullvisitorid
    FROM as_fullvisitorids
    EXCEPT
    SELECT fullvisitorid
    FROM a_fullvisitorids
);

CREATE OR REPLACE TEMPORARY VIEW a_exclusive_vid AS (
    SELECT visitid
    FROM a_visitids
    EXCEPT
    SELECT visitid
    FROM as_visitids
);

CREATE OR REPLACE TEMPORARY VIEW as_exclusive_vid AS (
    SELECT visitid
    FROM as_visitids
    EXCEPT
    SELECT visitid
    FROM a_visitids
);

 * postgresql://postgres:***@localhost/ecomm_cleanse
Done.
Done.
Done.
Done.


[]

In [306]:
%%sql
SELECT COUNT(*) FROM a_exclusive_fvid;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(116388,)]

In [307]:
%%sql
SELECT COUNT(*) FROM as_exclusive_fvid;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(0,)]

In [308]:
%%sql
SELECT COUNT(*) FROM a_exclusive_vid;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(144982,)]

In [309]:
%%sql
SELECT COUNT(*) FROM as_exclusive_vid;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(0,)]

- if we filter all_sessions for the same date range as analytics, it appears that it does not have any unique visitors or visit records that don't also appear in analytics
    - this implies that all_sessions is reserved for recording more specific types of user interactions on the site
    - therefore analytics having unique records is not itself indicative of a data quality issue, it's likely that all_sessions data is aggregative analytics data
        - using this hypothesis, the high number of fullvisitorid and visitids exclusive to analytics might imply that these visits did not amount to anything worth recording into all_sessions (e.g., no transaction, no add to cart, etc)

- lets try to explore a few visitids that appear in both tables, one with a recorded transaction, and one without, to see if we can confirm the above hypothesis

In [310]:
%%sql
SELECT (
    SELECT visitid
    FROM all_sessions
    RIGHT JOIN as_visitids USING (visitid)
    WHERE transactions IS NULL
    LIMIT 1
) AS null_transaction,
(
    SELECT visitid
    FROM all_sessions
    RIGHT JOIN as_visitids USING (visitid)
    WHERE transactions IS NOT NULL
    LIMIT 1
) AS transaction;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[('1498687471', '1495668283')]

In [311]:
%sql SELECT COUNT(*) FROM analytics WHERE visitid != visitstarttime

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(13678,)]

- visitid is assigned based on visitstarttime in almost all cases

In [312]:
%%sql
SELECT *
FROM analytics
JOIN as_visitids USING (visitid)
WHERE visitid != visitstarttime LIMIT 3;

 * postgresql://postgres:***@localhost/ecomm_cleanse
3 rows affected.


[('1496291847', '1', '1496291903', datetime.date(2017, 5, 31), '7043414484996997563', 'Direct', 'Not Socially Engaged', None, '7', '254', None, None, Decimal('12.99')),
 ('1496291847', '1', '1496291903', datetime.date(2017, 5, 31), '7043414484996997563', 'Direct', 'Not Socially Engaged', None, '7', '254', None, None, Decimal('13.99')),
 ('1496291847', '1', '1496291903', datetime.date(2017, 5, 31), '7043414484996997563', 'Direct', 'Not Socially Engaged', None, '7', '254', None, None, Decimal('14.99'))]

- where visistartime != visitid, its usually only off by a few seconds
    - e.g., 149443961**4** vs 149443961**1**
    - this may become relevant later if we attempt to clean these columns
        - we'll have to check if there are `visitid`s belonging to multiple `fullvisitorid`s, and that whichever we choose to resolve the discrepancies, its not creating more problems

- next we'll join the relevant columns from `analytics` and `all_sessions`, filtering for a single `visitid`
    - we'll use one visitid with no associated transaction, and one with a transaction, to try to inferr what the purpose of each table is, and why so many `fullvisitorid`s and `visitid`s are not present inside `all_sessions`

In [313]:
%%sql

SELECT DISTINCT a.fullvisitorid, a.visitid, a.date, a.pageviews, a.timeonsite, a.visitstarttime, s.totaltransactionrevenue, a.revenue, s.v2productname, s.productprice, a.unitprice, s.productquantity, a.unitssold
FROM all_sessions s
RIGHT JOIN analytics a USING (visitid, fullvisitorid, date, pageviews)
WHERE visitid = '1498687471'

 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[('5153038635419747224', '1498687471', datetime.date(2017, 6, 28), '2', '9', '1498687471', None, None, "YouTube Men's Short Sleeve Hero Tee Charcoal", Decimal('18.99'), Decimal('1.99'), None, None),
 ('5153038635419747224', '1498687471', datetime.date(2017, 6, 28), '2', '9', '1498687471', None, None, "YouTube Men's Short Sleeve Hero Tee Charcoal", Decimal('18.99'), Decimal('4.99'), None, None),
 ('5153038635419747224', '1498687471', datetime.date(2017, 6, 28), '2', '9', '1498687471', None, None, "YouTube Men's Short Sleeve Hero Tee Charcoal", Decimal('18.99'), Decimal('6.99'), None, None),
 ('5153038635419747224', '1498687471', datetime.date(2017, 6, 28), '2', '9', '1498687471', None, None, "YouTube Men's Short Sleeve Hero Tee Charcoal", Decimal('18.99'), Decimal('10.99'), None, None),
 ('5153038635419747224', '1498687471', datetime.date(2017, 6, 28), '2', '9', '1498687471', None, None, "YouTube Men's Short Sleeve Hero Tee Charcoal", Decimal('18.99'), Decimal('14.99'), None, None),
 ('5153038635419747224', '1498687471', datetime.date(2017, 6, 28), '2', '9', '1498687471', None, None, "YouTube Men's Short Sleeve Hero Tee Charcoal", Decimal('18.99'), Decimal('16.99'), None, None),
 ('5153038635419747224', '1498687471', datetime.date(2017, 6, 28), '2', '9', '1498687471', None, None, "YouTube Men's Short Sleeve Hero Tee Charcoal", Decimal('18.99'), Decimal('18.99'), None, None),
 ('5153038635419747224', '1498687471', datetime.date(2017, 6, 28), '2', '9', '1498687471', None, None, "YouTube Men's Short Sleeve Hero Tee Charcoal", Decimal('18.99'), Decimal('19.99'), None, None),
 ('5153038635419747224', '1498687471', datetime.date(2017, 6, 28), '2', '9', '1498687471', None, None, "YouTube Men's Short Sleeve Hero Tee Charcoal", Decimal('18.99'), Decimal('20.99'), None, None),
 ('5153038635419747224', '1498687471', datetime.date(2017, 6, 28), '2', '9', '1498687471', None, None, "YouTube Men's Short Sleeve Hero Tee Charcoal", Decimal('18.99'), Decimal('29.99'), None, None)]

- the above result doesn't give us much insight
    - its interesting that `pageviews` doesn't correlate with the amount of records found in `analytics`

- lets confirm how many records are associated with this `visitid` in each table

In [314]:
%%sql

SELECT (
    SELECT COUNT(*)
    FROM all_sessions
    WHERE visitid = '1498687471'
) AS all_sessions_records,
(
    SELECT COUNT(*)
    FROM analytics
    WHERE visitid = '1498687471'
) AS analytics_records


 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(1, 10)]

- this a 10:1 ratio for this `visitid`s records, `analytics`:`all_sessions`

- lets see what the average is for all `visitid`s

In [316]:
%%sql
SELECT (
    WITH a_vid_count AS (
        SELECT visitid, COUNT(*)
        FROM analytics
        GROUP BY visitid
    )
    SELECT AVG(count)::NUMERIC(10,2)
    FROM a_vid_count
) AS avg_analytics_records_per_visit,
(
    WITH s_vid_count AS (
        SELECT visitid, COUNT(*)
        FROM all_sessions
        WHERE date BETWEEN '2017-05-01' AND '2017-08-01'
        GROUP BY visitid
    )
    SELECT AVG(count)::NUMERIC(10,2)
    FROM s_vid_count
) AS avg_all_sessions_records_per_visit


 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(Decimal('11.70'), Decimal('1.03'))]

- the average ratio is ~ 12:1, a typical `visitid` only appears once in `all_sessions`, and 12x in `analytics`

- now lets look at a visit that resulted in a transaction (where `all_sessions.transactions` is not null)

In [317]:
%%sql

SELECT DISTINCT s.fullvisitorid, s.visitid, s.date, s.pageviews, s.timeonsite, a.visitstarttime, s.totaltransactionrevenue, a.revenue, s.v2productname, s.productprice, a.unitprice, s.productquantity, a.unitssold
FROM all_sessions s
FULL JOIN analytics a USING (visitid, fullvisitorid, date, pageviews)
WHERE visitid = '1495668283'

 * postgresql://postgres:***@localhost/ecomm_cleanse
17 rows affected.


[('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), Decimal('11.13'), "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('10.63'), None, '1'),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), Decimal('15.69'), "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('15.19'), None, '1'),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('0.00'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('3.99'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('4.79'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('10.39'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('10.63'), None, '1'),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('10.63'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('11.19'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('14.39'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('15.19'), None, '1'),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('15.19'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('15.99'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('18.99'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('19.19'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('19.99'), None, None),
 ('086102919761743448', '1495668283', datetime.date(2017, 5, 24), '12', '391', '1495668283', Decimal('26.82'), None, "Google Men's Vintage Badge Tee Sage", Decimal('10.63'), Decimal('23.19'), None, None)]

- revenue only shows up in 2 of the 17 records for this `visitid` in `analytics` table
    - but the two `revenue` values in `analytics` sum to `totaltransactionrevenue` in `all_sessions`
- `analytics.unitssold` appears non-null where revenue is non-null, and once again where it is null, but shares the same `unitprice`, indicating that this record is associated with the same product

- lets see if the `revenue`-`totaltransactionrevenue` holds for other `visitid`s by summing the `revenue` values for each `visitid`

In [322]:
%%sql

SELECT a.visitid, totaltransactionrevenue, SUM(revenue) as sum_revenue
FROM analytics a
JOIN all_sessions s USING (visitid)
WHERE totaltransactionrevenue IS NOT NULL
    AND revenue IS NOT NULL
GROUP BY a.visitid, totaltransactionrevenue
ORDER BY visitid;

 * postgresql://postgres:***@localhost/ecomm_cleanse
22 rows affected.


[('1493668365', Decimal('81.96'), Decimal('46.98')),
 ('1494587162', Decimal('16.99'), Decimal('16.99')),
 ('1494613832', Decimal('8.98'), Decimal('8.98')),
 ('1494618681', Decimal('71.19'), Decimal('71.19')),
 ('1494701566', Decimal('123.00'), Decimal('123.00')),
 ('1494979981', Decimal('16.99'), Decimal('16.99')),
 ('1495027160', Decimal('61.97'), Decimal('40.32')),
 ('1495462087', Decimal('22.99'), Decimal('22.99')),
 ('1495668283', Decimal('26.82'), Decimal('26.82')),
 ('1495753948', Decimal('12.19'), Decimal('12.19')),
 ('1495892360', Decimal('57.99'), Decimal('57.99')),
 ('1495994469', Decimal('396.00'), Decimal('396.00')),
 ('1496601172', Decimal('391.00'), Decimal('391.00')),
 ('1496684037', Decimal('324.00'), Decimal('324.00')),
 ('1497025570', Decimal('35.99'), Decimal('35.99')),
 ('1497055585', Decimal('306.00'), Decimal('306.00')),
 ('1497459609', Decimal('23.99'), Decimal('23.99')),
 ('1498252156', Decimal('115.52'), Decimal('103.83')),
 ('1499007891', Decimal('63.97'), Decimal('63.98')),
 ('1499924733', Decimal('649.24'), Decimal('609.28')),
 ('1500066377', Decimal('358.00'), Decimal('358.00')),
 ('1501014103', Decimal('151.00'), Decimal('151.00'))]

- it appears that summed `analytics.revenue` is equal to `totaltransactionrevenue` in the majority of cases, this would indicate an issue where they don't agree
- lets isolate the `visitid`s that don't conform to this pattern

In [326]:
%%sql
WITH revenue_discrepancy AS (
    WITH revenue_comparsion AS (
        SELECT a.visitid, totaltransactionrevenue, SUM(revenue) as sum_revenue
        FROM analytics a
        JOIN all_sessions s USING (visitid)
        WHERE totaltransactionrevenue IS NOT NULL
            AND revenue IS NOT NULL
        GROUP BY a.visitid, totaltransactionrevenue
        ORDER BY visitid
    )
    SELECT visitid
    FROM revenue_comparsion
    WHERE totaltransactionrevenue != sum_revenue
)

SELECT DISTINCT * FROM analytics WHERE visitid IN (SELECT visitid FROM revenue_discrepancy LIMIT 1);

 * postgresql://postgres:***@localhost/ecomm_cleanse
29 rows affected.


[('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', '1', '17', '732', None, Decimal('17.49'), Decimal('15.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', '1', '17', '732', None, Decimal('29.49'), Decimal('27.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', '1', '17', '732', None, None, Decimal('15.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', '1', '17', '732', None, None, Decimal('27.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('0.00')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('0.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('1.50')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('1.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('3.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('4.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('5.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('8.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('15.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('16.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('17.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('18.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('19.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('20.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('21.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('24.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('27.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic Search', 'Not Socially Engaged', None, '17', '732', None, None, Decimal('28.99')),
 ('1', '1493668365', '1493668365', datetime.date(2017, 5, 1), '1862546724568841127', 'Organic 

In [ ]:
17.49 / 15.99, 29.49 / 27.99, 15.99 * 2 + 27.99 * 2

(1.0938086303939962, 1.0535905680600215, 87.96)

- trying to make sense of why totaltransactionrevenue is almost double what the summed revenue is for visitid = 1493668365
- looking at the records where unitssold is 1, adding these up gets us closer to totaltransactionrevenue. perhaps revenue didn't get recorded correctly?
    - makes it uncertain which revenue value to trust. would assume the larger value is more accurate. totaltransactionrevenue would be less likely to get inflated for no reason?


- lets look at all_sessions for the same visitid = 1493668365

In [333]:
%sql SELECT visitid, totaltransactionrevenue, productprice, productquantity, productrevenue FROM all_sessions WHERE visitid = '1493668365'

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[('1493668365', Decimal('81.96'), Decimal('21.99'), None, None)]

- its problematic that priceprice doesn't correlate with the unitprice found in analytics associated with the revenue
    - though there is a record with null revenue that matches this productprice (21.99)

### totaltransctionrevenue - revenue disparity

- investigate:
    - `visitid`s that have `totaltransactionrevenue` in `all_sessions`, but no `revenue` in `analytics`
        - the inverse of above, `visitid`s that have `revenue` in `analytics` but no corresponding `totaltransactionrevenue` in `all_sessions`

In [351]:
%%sql

SELECT DISTINCT ON(a.visitid) a.visitid, a.date, a.pageviews, s.totaltransactionrevenue, a.revenue,s.productprice, a.unitprice, s.productquantity, a.unitssold
FROM all_sessions s
FULL JOIN analytics a USING (visitid)
WHERE s.totaltransactionrevenue IS NULL
    AND a.revenue IS NOT NULL
LIMIT 10;


 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[('1493621769', datetime.date(2017, 5, 1), '2', None, Decimal('157.00'), None, Decimal('149.00'), None, '1'),
 ('1493627652', datetime.date(2017, 5, 1), '19', None, Decimal('242.00'), None, Decimal('79.00'), None, '3'),
 ('1493645645', datetime.date(2017, 5, 1), '13', None, Decimal('71.68'), None, Decimal('33.59'), None, '2'),
 ('1493646617', datetime.date(2017, 5, 1), '15', None, Decimal('41.59'), None, Decimal('33.59'), None, '1'),
 ('1493647016', datetime.date(2017, 5, 1), '15', None, Decimal('41.59'), None, Decimal('33.59'), None, '1'),
 ('1493647067', datetime.date(2017, 5, 1), '11', None, Decimal('38.59'), None, Decimal('33.59'), None, '1'),
 ('1493647384', datetime.date(2017, 5, 1), '18', None, Decimal('37.59'), None, Decimal('33.59'), None, '1'),
 ('1493647545', datetime.date(2017, 5, 1), '18', None, Decimal('41.59'), None, Decimal('33.59'), None, '1'),
 ('1493647615', datetime.date(2017, 5, 1), '27', None, Decimal('14.49'), None, Decimal('12.99'), None, '1'),
 ('1493647743', datetime.date(2017, 5, 1), '23', None, Decimal('5.51'), None, Decimal('1.59'), None, '2')]

- there are clearly many instances where revenue is recorded in `analytics`, without any `totaltransactionrevenue` being recorded in `all_sessions`
- lets count how many

In [352]:
%%sql

SELECT COUNT(*)
FROM (
    SELECT DISTINCT ON (a.visitid) a.visitid, a.date, a.pageviews, s.totaltransactionrevenue, a.revenue,s.productprice, a.unitprice, s.productquantity, a.unitssold
    FROM all_sessions s
    FULL JOIN analytics a USING (visitid)
    WHERE s.totaltransactionrevenue IS NULL
        AND a.revenue IS NOT NULL
)

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(6375,)]

- there are 6375 unique visits with with a non-null revenue value in analytics where there is no totaltransactionrevenue recorded in all_sessions
    - this implies that all_sessions is incomplete, and is not effectively aggregating data from analytics

- lets check if there are instances of recorded totaltransactionrevenue in all_sessions where there is no corresponding revenue recorded in analytics

In [370]:
%%sql

SELECT DISTINCT ON (s.visitid) s.visitid, s.date, a.pageviews, s.totaltransactionrevenue, a.revenue,s.productprice, a.unitprice, s.productquantity, a.unitssold
FROM all_sessions s
FULL JOIN analytics a USING (visitid)
WHERE s.totaltransactionrevenue IS NOT NULL
    AND a.revenue IS NULL
    AND s.date BETWEEN '2017-05-01' AND '2017-08-02'
ORDER BY visitid;

 * postgresql://postgres:***@localhost/ecomm_cleanse
22 rows affected.


[('1493668365', datetime.date(2017, 5, 1), '17', Decimal('81.96'), None, Decimal('21.99'), Decimal('21.99'), None, None),
 ('1494587162', datetime.date(2017, 5, 12), '14', Decimal('16.99'), None, Decimal('24.99'), Decimal('29.99'), None, None),
 ('1494613832', datetime.date(2017, 5, 12), '15', Decimal('8.98'), None, Decimal('5.59'), Decimal('79.19'), None, None),
 ('1494618681', datetime.date(2017, 5, 12), '13', Decimal('71.19'), None, Decimal('55.99'), Decimal('64.99'), None, None),
 ('1494701566', datetime.date(2017, 5, 13), '12', Decimal('123.00'), None, Decimal('119.00'), Decimal('119.00'), None, '1'),
 ('1494979981', datetime.date(2017, 5, 16), '10', Decimal('16.99'), None, Decimal('15.99'), Decimal('15.99'), '1', '1'),
 ('1495027160', datetime.date(2017, 5, 17), '19', Decimal('61.97'), None, Decimal('19.99'), Decimal('0.00'), None, None),
 ('1495462087', datetime.date(2017, 5, 22), '15', Decimal('22.99'), None, Decimal('23.99'), Decimal('16.79'), None, None),
 ('1495668283', datetime.date(2017, 5, 24), '12', Decimal('26.82'), None, Decimal('10.63'), Decimal('19.19'), None, None),
 ('1495753948', datetime.date(2017, 5, 25), '18', Decimal('12.19'), None, Decimal('3.99'), Decimal('9.99'), None, None),
 ('1495892360', datetime.date(2017, 5, 27), '19', Decimal('57.99'), None, Decimal('2.99'), Decimal('15.99'), None, None),
 ('1495994469', datetime.date(2017, 5, 28), '12', Decimal('396.00'), None, Decimal('149.00'), Decimal('199.00'), None, None),
 ('1496601172', datetime.date(2017, 6, 4), '22', Decimal('391.00'), None, Decimal('149.00'), Decimal('149.00'), '1', '1'),
 ('1496684037', datetime.date(2017, 6, 5), '14', Decimal('324.00'), None, Decimal('79.00'), Decimal('238.00'), '1', None),
 ('1497025570', datetime.date(2017, 6, 9), '14', Decimal('35.99'), None, Decimal('16.99'), Decimal('33.99'), None, None),
 ('1497055585', datetime.date(2017, 6, 9), '10', Decimal('306.00'), None, Decimal('298.00'), Decimal('149.00'), None, None),
 ('1497459609', datetime.date(2017, 6, 14), '16', Decimal('23.99'), None, Decimal('34.99'), Decimal('29.99'), None, None),
 ('1498252156', datetime.date(2017, 6, 23), '15', Decimal('115.52'), None, Decimal('15.99'), Decimal('15.99'), None, '1'),
 ('1499007891', datetime.date(2017, 7, 2), '19', Decimal('63.97'), None, Decimal('4.99'), Decimal('18.99'), None, '1'),
 ('1499924733', datetime.date(2017, 7, 13), '48', Decimal('649.24'), None, Decimal('1.40'), Decimal('6.72'), None, None),
 ('1500066377', datetime.date(2017, 7, 14), '15', Decimal('358.00'), None, Decimal('119.00'), Decimal('119.00'), '1', '1'),
 ('1501014103', datetime.date(2017, 7, 25), '11', Decimal('151.00'), None, Decimal('149.00'), Decimal('199.00'), None, None)]

- there are also 23 unique visits that have no recorded revenue in `anlaytics`, yet have a `totaltransactionrevenue` recorded in `all_sessions`

- so unfortunately, we can't point to either `all_sessions` or `analytics` as a complete source of customer transactions. they are both incomplete
    - it also becomes much harder to determine which one to defer to if there is a discrepancy
        - for now, there are far fewer transactions that seem missing from analytics, so lets try to fill in this missing information using `totaltransactionrevenue`

In [369]:
%%sql
SELECT DISTINCT ON (visitid) visitid, revenue
FROM analytics
WHERE visitid IN (
    SELECT DISTINCT ON (s.visitid) s.visitid
    FROM all_sessions s
    FULL JOIN analytics a USING (visitid)
    WHERE s.totaltransactionrevenue IS NOT NULL
        AND a.revenue IS NULL
        AND s.date BETWEEN '2017-05-01' AND '2017-08-02'
)
    AND revenue IS NOT NULL
ORDER BY visitid

 * postgresql://postgres:***@localhost/ecomm_cleanse
22 rows affected.


[('1493668365', Decimal('29.49')),
 ('1494587162', Decimal('16.99')),
 ('1494613832', Decimal('6.09')),
 ('1494618681', Decimal('71.19')),
 ('1494701566', Decimal('123.00')),
 ('1494979981', Decimal('16.99')),
 ('1495027160', Decimal('18.66')),
 ('1495462087', Decimal('22.99')),
 ('1495668283', Decimal('11.13')),
 ('1495753948', Decimal('12.19')),
 ('1495892360', Decimal('57.99')),
 ('1495994469', Decimal('396.00')),
 ('1496601172', Decimal('239.50')),
 ('1496684037', Decimal('82.50')),
 ('1497025570', Decimal('35.99')),
 ('1497055585', Decimal('306.00')),
 ('1497459609', Decimal('23.99')),
 ('1498252156', Decimal('30.88')),
 ('1499007891', Decimal('39.66')),
 ('1499924733', Decimal('8.84')),
 ('1500066377', Decimal('238.50')),
 ('1501014103', Decimal('151.00'))]

- as it turns out, the previous conclusion was not correct
    - the previous `all_sessions` query returned results from `analytics` where `visitid`s were paired with null `revenue`, however, i forgot that there are multiple entires for a given `visitid` in `analytics`
    - all 22 of the `visitid`s actually have a `revenue` value
        - in conclusion, there are no `totaltransactionrevenue` values in `all_sessions` that don't have corresponding `revenue` values in `analytics`
            - therefore `analytics` is the complete table, and `all_sessions` is missing certain transactions (assuming that `revenue` is in fact indicative of a transaction taking place)

- we can easily confirm this by collected the `visitid`s from `all_sessions` and using them to filter for non-null `revenue` records in `analytics`

In [375]:
%%sql

SELECT COUNT(DISTINCT visitid)
FROM all_sessions
WHERE totaltransactionrevenue IS NOT NULL
    AND date BETWEEN '2017-05-01' AND '2017-08-01';

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(22,)]

In [377]:
%%sql

SELECT COUNT(*)
FROM (
    SELECT DISTINCT ON (visitid) * FROM analytics
    WHERE visitid IN (SELECT visitid FROM all_sessions WHERE totaltransactionrevenue IS NOT NULL)
        AND revenue IS NOT NULL
)

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(22,)]

- the only way the count from the two most recent queries can be the same number, is if every visitid in all_sessions associated with a non-null totaltransactionrevenue has a corresponding non-null revenue value found in analytics

- now lets find out how many transactions are missing from `all_sessions` based on the the records found in `analytics`

In [74]:
%%sql

SELECT COUNT(DISTINCT visitid)
FROM analytics
WHERE visitid NOT IN (
    SELECT visitid
    FROM all_sessions
    WHERE totaltransactionrevenue IS NOT NULL
        AND date BETWEEN '2017-05-01' AND '2017-08-01'
)
    AND revenue IS NOT NULL;

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(6375,)]

- there are 6375 visits with recorded `revenue` (which we are assuming indicates a transaction), that have no associated `totaltransactionrevenue` in `all_sessions`

- how many of these `visitid`s are present in `all_sessions`, but are merely missing contain null `totaltransactionrevenue`?
- how many of these `visitid`s are missing entirely from `all_sessions`?

In [93]:
%%sql

WITH analytics_revenue_discrepancy AS (
    SELECT DISTINCT ON (visitid) * FROM analytics
    WHERE visitid NOT IN (
        SELECT visitid
        FROM all_sessions
        WHERE totaltransactionrevenue IS NOT NULL
            AND date BETWEEN '2017-05-01' AND '2017-08-01'
    )
        AND revenue IS NOT NULL
)

SELECT s.visitid, s.totaltransactionrevenue, SUM(a.revenue) as total_analytics_revenue
FROM all_sessions s
JOIN analytics a USING (visitid)
WHERE s.visitid IN (SELECT visitid FROM analytics_revenue_discrepancy)
    AND a.revenue IS NOT NULL
GROUP BY visitid, totaltransactionrevenue;


 * postgresql://postgres:***@localhost/ecomm_cleanse
5 rows affected.


[('1494530759', None, Decimal('244.00')),
 ('1496874103', None, Decimal('153.00')),
 ('1499809854', None, Decimal('84.76')),
 ('1501191783', None, Decimal('32.99')),
 ('1501606687', None, Decimal('1002.78'))]

- the above `visitid`s are present in both `analytics` and `all_sessions`, but represent a discrepancy regarding the presence of a transaction
    - `all_sessions` has null `totaltransactionrevenue`
    - `analytics' has non-null `revenue`

- given that we've already established that `totaltransactionrevenue` = SUM('revenue') for a given `visitid`, we can draw 1 of two conclusions:
    1. that `all_sessions` is missing `totaltransactionrevenue` data for transactions that occured
    2. that `analytics.revenue` is not a true indicator of whether a transaction occured


#### unitssold, unitprice, and revenue

- how do these columns correlate? is revenue = unitssold * unitprice?

In [70]:
%%sql

SELECT visitid, revenue, unitssold, unitprice, (unitssold::INT * unitprice) AS productrevenue
FROM analytics
WHERE visitid NOT IN (
    SELECT visitid
    FROM all_sessions
    WHERE totaltransactionrevenue IS NOT NULL
        AND date BETWEEN '2017-05-01' AND '2017-08-01'
)
    AND revenue IS NOT NULL
LIMIT 10;

 * postgresql://postgres:***@localhost/ecomm_cleanse
10 rows affected.


[('1496336798', Decimal('106.48'), '12', Decimal('8.79'), Decimal('105.48')),
 ('1496337267', Decimal('15.13'), '1', Decimal('10.63'), Decimal('10.63')),
 ('1496337267', Decimal('15.69'), '1', Decimal('11.19'), Decimal('11.19')),
 ('1496340255', Decimal('122.00'), '1', Decimal('119.00'), Decimal('119.00')),
 ('1496340255', Decimal('479.00'), '4', Decimal('119.00'), Decimal('476.00')),
 ('1496342860', Decimal('153.50'), '1', Decimal('149.00'), Decimal('149.00')),
 ('1496342860', Decimal('83.50'), '1', Decimal('79.00'), Decimal('79.00')),
 ('1496343286', Decimal('16.32'), '1', Decimal('15.99'), Decimal('15.99')),
 ('1496345100', Decimal('11.63'), '1', Decimal('10.63'), Decimal('10.63')),
 ('1496345100', Decimal('120.00'), '1', Decimal('119.00'), Decimal('119.00'))]

### productprice

- where is `productprice` coming from? when does it match `unitprice` in `analytics`

## Missing data

- exploring the columns that have a high amount of nulls or 0s

### `all_sessions.productprice`

In [279]:
%%sql

SELECT COUNT(*) FROM all_sessions WHERE productprice = '0';

 * postgresql://postgres:***@localhost/ecomm_cleanse
1 rows affected.


[(376,)]

- there are many records where product price is 0, it should be probably be null, as the product isn't free, the data is just missing
    - lets check to ensure this doesn't represent non-product pages

In [280]:
%%sql

SELECT * FROM all_sessions WHERE productprice = '0' LIMIT 3;

 * postgresql://postgres:***@localhost/ecomm_cleanse
3 rows affected.


[('363353355754397151', 'Direct', '0', 'Hong Kong', 'Hong Kong', None, None, '29', '2', None, datetime.date(2017, 2, 12), '1486902812', 'PAGE', None, Decimal('0.00'), None, '9182859', 'Google Toddler Raglan Shirt Blue Heather/Navy', '(not set)', '(not set)', 'USD', None, None, 'The Google Merchandise Store/BRIGHTtravels Seat Pack Organizer', '/google+redesign/', '0', '1', None),
 ('5814496392054660145', 'Direct', '87417', 'United States', 'not available in demo dataset', None, None, '87', '7', None, datetime.date(2016, 9, 21), '1474513949', 'PAGE', None, Decimal('0.00'), None, '9182752', "Google Men's Short Sleeve Performance Badge Tee Charcoal", '(not set)', '(not set)', 'USD', None, None, "Google Men's Watershed Full Zip Hoodie Grey", '/google+redesign/', '0', '1', None),
 ('3369223998788703022', 'Organic Search', '0', 'Canada', 'not available in demo dataset', None, None, '145', '3', None, datetime.date(2016, 9, 22), '1474548525', 'PAGE', None, Decimal('0.00'), None, '9182772', "Google Women's Performance Full Zip Jacket Black", '(not set)', '(not set)', 'USD', None, None, 'Google Rucksack', '/google+redesign/', '0', '1', None)]

- these records have an associated `productsku`, so its safe to assume that `productprice` = 0 is actually missing data